import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {openStore} from '../server/store.mjs';
import {createOrganizations} from '../server/organizations.mjs';
import {createOrganizationAi} from '../server/organization-ai.mjs';
import {createOrganizationNotifications} from '../server/organization-notifications.mjs';
import {createWechat} from '../server/wechat.mjs';
import {createVoice} from '../server/voice.mjs';
import {entrySchema} from '../server/schema.mjs';
import {taskContentSchema,taskAssignmentSchema} from '../server/organization-schema.mjs';
import {encodeVoiceWav} from '../server/voice-audio.mjs';
const uid=()=>randomUUID(),now=()=>new Date().toISOString();
function fixture(t){const dir=mkdtempSync('/tmp/me-org-unit-'),store=openStore(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});const org=createOrganizations({store,secret:'fixture-secret',origin:'http://localhost'}),users=Array.from({length:5},(_,i)=>{const id=uid();store.db.prepare('INSERT INTO users(id,email,verified_at,created_at) VALUES (?,?,?,?)').run(id,`org-${i}@example.test`,now(),now());return id;}),[owner,manager,employee,other,stranger]=users,oid=uid();org.create(owner,{id:oid,name:'测试组织'});const ctx=(u=owner,id=oid)=>org.context(u,id);const act=(u,kind,data,version)=>org.mutate(ctx(u),{operationId:uid(),...(version?{version}:{}),data},kind);for(const u of [manager,employee,other]){const i=act(owner,'invite',{email:store.db.prepare('SELECT email FROM users WHERE id=?').get(u).email,role:u===manager?'admin':'member'});org.join(u,{code:new URL(org.invitationLink(ctx(),i.invitationId)).hash.slice(12)});}const create=(u=owner,a={},content={})=>{const id=uid();act(u,'create-tasks',{tasks:[{id,content:{body:'完成报价',...content},assignment:{assigneeId:employee,...a}}]});return id;};const task=(u,id)=>org.detail(ctx(u),id).task;const change=(u,id,kind,payload={})=>act(u,kind,{id,payload},task(u,id).version);return {store,org,users,owner,manager,employee,other,stranger,oid,ctx,act,create,task,change};}
const denied=(fn,status=403)=>assert.throws(fn,e=>e.status===status);
test('organization isolation includes private records, drafts, counts, read-only shares and exports',t=>{const f=fixture(t),{store,org,owner,manager,employee,other,stranger,ctx,act,create,task}=f;const privateEntry=entrySchema.parse({id:uid(),kind:'note',body:'私密原文，不可公开'});store.forUser(employee).mutate({operationId:uid(),baseVersion:0,entry:privateEntry},'fixture');const id=create();denied(()=>task(other,id),404);denied(()=>task(stranger,id),404);assert.equal(org.listTasks(ctx(other),{q:'报价'}).length,0);assert.equal(store.forUser(owner).list().length,0);assert.equal(store.forUser(employee).list().length,1);assert.equal(org.exportData(ctx()).tasks.length,1);denied(()=>org.exportData(ctx(employee)));
 const draft=uid();act(employee,'create-tasks',{tasks:[{id:draft,content:{body:'私人的组织草稿'},assignment:{assigneeId:employee},publish:false}]});denied(()=>task(manager,draft),404);assert.equal(org.listTasks(ctx()).length,1);
 const sid=uid();act(employee,'share',{id:sid,sourceId:privateEntry.id,sourceVersion:1,snapshot:{body:'选定的公开片段'},recipients:[other],visibility:'recipients',scopeId:null});assert.equal(org.shares(ctx()).length,0);assert.equal(org.shares(ctx(manager)).length,0);assert.equal(org.shares(ctx(other))[0].snapshot.body,'选定的公开片段');assert.equal(org.shares(ctx(other))[0].sourceId,undefined);store.forUser(employee).mutate({operationId:uid(),baseVersion:1,entry:{...privateEntry,body:'后续私人修改'}},'fixture');assert.equal(org.shares(ctx(other))[0].snapshot.body,'选定的公开片段');act(employee,'revoke-share',{id:sid},1);assert.equal(org.shares(ctx(other)).length,0);assert.equal(JSON.stringify(org.exportData(ctx())).includes('后续私人修改'),false);
 const otherOrg=uid();org.create(stranger,{id:otherOrg,name:'另一个组织'});denied(()=>org.detail(org.context(stranger,otherOrg),id),404);
});
test('assignment, acceptance, submission and review cannot be bypassed by execution updates',t=>{const f=fixture(t),{owner,manager,employee,other,create,task,change}=f;const id=create(owner,{reviewRequired:true,reviewerId:owner,acceptRequired:true});denied(()=>change(employee,id,'content',{body:'擅改截止'}));denied(()=>change(employee,id,'assignment',{assigneeId:other}));denied(()=>change(employee,id,'approve'));assert.throws(()=>change(employee,id,'complete',{note:'已完成'}),/确认接收/);change(employee,id,'accept');change(employee,id,'start');change(employee,id,'complete',{note:'报价文件已交付'});assert.equal(task(owner,id).status,'review');denied(()=>change(employee,id,'approve'));denied(()=>change(employee,id,'complete'));change(owner,id,'return',{note:'补充税费'});assert.equal(task(employee,id).status,'doing');change(employee,id,'complete',{note:'已补充'});change(owner,id,'approve',{note:'通过'});assert.equal(task(employee,id).status,'done');assert.equal(task(employee,id).submittedAt!==null,true);
 const self=create(owner,{assigneeId:manager,reviewerId:owner,reviewRequired:true});change(manager,self,'complete',{note:'交付'});denied(()=>change(manager,self,'approve'));change(owner,self,'approve');
});
test('version conflicts and idempotency preserve single task and single notification',t=>{const f=fixture(t),{org,owner,employee,other,ctx,act,create,task,change,store}=f;const id=uid(),op={operationId:uid(),data:{tasks:[{id,content:{body:'单次任务'},assignment:{assigneeId:employee}}]}};org.mutate(ctx(),op,'create-tasks');org.mutate(ctx(),op,'create-tasks');assert.equal(org.listTasks(ctx()).length,1);assert.equal(org.notifications(ctx(employee)).length,1);const v=task(owner,id).version;change(owner,id,'content',{...task(owner,id).content,dueDate:'2027-01-01'});denied(()=>act(owner,'content',{id,payload:{body:'过期编辑'}},v),409);assert.equal(task(owner,id).content.dueDate,'2027-01-01');assert.equal(store.forUser(employee).exportData().entries.length,0);});
test('scoped leaders can manage only current authorized scope; target scope is checked',t=>{const f=fixture(t),{owner,employee,other,manager,ctx,act,create,task,change}=f;const p=uid(),p2=uid();act(owner,'scope',{id:p,name:'项目 A',kind:'project',leadId:employee,memberIds:[employee,other]});act(owner,'scope',{id:p2,name:'项目 B',kind:'project',leadId:null,memberIds:[other]});const a=create(owner,{projectId:p,assigneeId:other}),b=create(owner,{projectId:p2,assigneeId:other});assert.equal(task(employee,a).permissions.manage,true);denied(()=>task(employee,b),404);denied(()=>change(employee,a,'assignment',{...taskAssignmentSchema.parse({}),assigneeId:other,projectId:p2}));act(owner,'scope',{id:p,name:'项目 A',kind:'project',leadId:null,memberIds:[other]},1);denied(()=>task(employee,a),404);});
test('removal immediately revokes access while leaving work for handover and personal account intact',t=>{const f=fixture(t),{org,store,owner,employee,other,ctx,act,create,task,change}=f;const id=create(),old=ctx(employee).member;act(owner,'member',{id:employee,name:old.name,role:old.role,state:'disabled',departmentId:null},old.version);denied(()=>task(employee,id),404);assert.equal(org.list(employee).length,0);assert.equal(store.db.prepare('SELECT id FROM users WHERE id=?').get(employee).id,employee);const a=task(owner,id);change(owner,id,'assignment',{...taskAssignmentSchema.parse({}),assigneeId:other});assert.equal(task(other,id).assigneeId,other);assert.equal(task(owner,id).creatorId,owner);});
test('invitations bind verified email, expire, revoke, and ownership transfer requires recipient acceptance',t=>{const f=fixture(t),{org,store,owner,manager,employee,stranger,ctx,act,oid}=f;const invitation=act(owner,'invite',{email:'org-4@example.test'}),code=new URL(org.invitationLink(ctx(),invitation.invitationId)).hash.slice(12);assert.throws(()=>org.join(employee,{code}),/邮箱/);act(owner,'revoke-invitation',{id:invitation.invitationId});assert.throws(()=>org.join(stranger,{code}),/失效/);denied(()=>act(manager,'invite',{email:'new@example.test',role:'admin'}));assert.throws(()=>act(owner,'member',{id:owner,name:'owner',role:'member',state:'left',departmentId:null},ctx().member.version),/所有者/);act(owner,'transfer',{to:employee},ctx().org.version);assert.equal(ctx(employee).member.role,'member');act(employee,'transfer',{to:null,accept:true},ctx(employee).org.version);assert.equal(ctx(employee).member.role,'owner');assert.equal(ctx(owner).member.role,'admin');});
test('change requests preserve original deadline; stale approval is rejected; batch actions are atomic',t=>{const f=fixture(t),{owner,employee,other,ctx,act,create,task,change,org}=f;const a=create(owner,{}, {dueDate:'2027-01-01'}),b=create();change(employee,a,'request',{kind:'deadline',reason:'需要更多时间',dueDate:'2027-01-03'});let request=org.detail(ctx(),a).requests[0];change(owner,a,'content',{...task(owner,a).content,title:'新版本'});denied(()=>change(owner,a,'resolve-request',{requestId:request.id,approved:true,note:''}),409);change(owner,a,'resolve-request',{requestId:request.id,approved:false,note:'重新申请'});change(employee,a,'request',{kind:'deadline',reason:'更新后的申请',dueDate:'2027-01-03'});request=org.detail(ctx(),a).requests[0];change(owner,a,'resolve-request',{requestId:request.id,approved:true,note:'可以'});assert.equal(task(owner,a).content.dueDate,'2027-01-03');assert.equal(task(owner,a).originalDue,'2027-01-01');denied(()=>act(owner,'batch',{items:[{id:a,version:task(owner,a).version},{id:b,version:99}],action:'assign',assigneeId:other}),409);assert.equal(task(owner,a).assigneeId,employee);});
test('PushPlus callback records delivery only; revoked recipients do not get outgoing content',async t=>{const f=fixture(t),{store,org,owner,employee,ctx,act,create,task}=f,sent=[];const wechat=createWechat({store,secret:'fixture',enabled:true,origin:'http://localhost',fetchOverride:async(url,request)=>{sent.push(JSON.parse(request.body));return new Response(JSON.stringify({code:200,data:'short-fixture'}));}}),notifications=createOrganizationNotifications({org,wechat,origin:'http://localhost'});wechat.bind(employee,'fixture-token-no-external-network');let c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,wechatEnabled:true}},c.org.version);act(employee,'preferences',{wechat:true,mode:'immediate',quietStart:'00:00',quietEnd:'00:00'});const id=create(owner,{}, {title:'敏感标题',body:'机密正文'});await notifications.tick();assert.equal(sent.length,1);assert.equal(sent[0].content.includes('机密'),false);assert.equal(sent[0].title.includes('敏感'),false);const token=sent[0].callbackUrl.split('/').at(-1);assert.equal(notifications.callback(token,{event:'message_complate',messageInfo:{shortCode:'short-fixture',sendStatus:2}}),true);assert.equal(org.notifications(ctx(employee))[0].acknowledgedAt,null);assert.equal(task(employee,id).status,'todo');const n=org.notifications(ctx(employee))[0];act(employee,'ack',{id:n.id});assert.equal(task(employee,id).status,'todo');
 const id2=create(),m=ctx(employee).member;act(owner,'member',{id:employee,name:m.name,role:'member',state:'disabled',departmentId:null},m.version);await notifications.tick();assert.equal(sent.length,1);});
test('personal reminder preferences do not change organization deadline or organization quadrant',t=>{const f=fixture(t),{owner,employee,create,task,change}=f,id=create(owner,{}, {dueDate:'2027-01-01',quadrant:'important'});change(employee,id,'task-preference',{muted:false,snoozeMinutes:30,quadrant:'later',focusDate:'2027-01-02'});assert.equal(task(employee,id).content.dueDate,'2027-01-01');assert.equal(task(employee,id).content.quadrant,'important');assert.equal(task(employee,id).preference.quadrant,'later');assert.equal(task(owner,id).preference.quadrant,undefined);});
test('organization AI opt-in, budget attribution and late revocation do not leak results or create tasks',async t=>{const f=fixture(t),{store,org,owner,employee,ctx,act}=f;let release;const ai=createOrganizationAi({store,org,config:{enabled:true,apiKey:'fixture'},fetchOverride:()=>new Promise(r=>release=r)});await assert.rejects(()=>ai.preview(ctx(employee),{id:uid(),text:'做报价',kind:'auto',consent:true}),e=>e.status===403);let c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,aiEnabled:true}},c.org.version);const pending=ai.preview(ctx(employee),{id:uid(),text:'做报价',kind:'auto',consent:true});assert.equal(store.db.prepare('SELECT org_id FROM ai_usage').get().org_id,f.oid);c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,aiEnabled:false}},c.org.version);release(new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'{}'}}]})));await assert.rejects(pending,e=>e.status===403);assert.equal(org.listTasks(ctx()).length,0);assert.equal(store.db.prepare('SELECT result FROM org_ai_previews').get().result,null);});
test('organization voice result cannot be retrieved via personal route or after settings change',async t=>{const f=fixture(t),{store,org,owner,employee,ctx,act}=f;const ai=createOrganizationAi({store,org,config:{enabled:true,apiKey:'fixture'}});let c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,voiceEnabled:true}},c.org.version);const voice=createVoice({store,config:{enabled:true,apiKey:'fixture'},fetchOverride:async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'组织转写'}}]}))}),samples=new Float32Array(16000).map((_,i)=>Math.sin(i/10)*.3),id=uid();const r=await voice.transcribe(employee,{id,audio:Buffer.from(encodeVoiceWav(samples)).toString('base64'),consent:true},ai.voiceContext(ctx(employee)));assert.equal(r.text,'组织转写');denied(()=>voice.result(employee,id),404);assert.equal(store.db.prepare('SELECT org_id FROM voice_usage').get().org_id,f.oid);c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,voiceEnabled:false}},c.org.version);denied(()=>ai.voiceContext(ctx(employee)));});
test('organization AI success returns editable suggestions, attributes shared costs and never publishes automatically',async t=>{const f=fixture(t),{org,store,owner,employee,ctx,act}=f;let c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,aiEnabled:true}},c.org.version);const ai=createOrganizationAi({store,org,config:{enabled:true,apiKey:'fixture'},fetchOverride:async()=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({items:[{kind:'task',title:'做报价',sourceText:'做报价',reminderAt:null}],advice:[]})}}],usage:{prompt_tokens:100,completion_tokens:50}}))}),input={id:uid(),text:'做报价',kind:'auto',consent:true};const r=await ai.preview(ctx(employee),input);assert.equal(r.items[0].kind,'task');assert.equal(r.items[0].body,'做报价');assert.equal(r.items[0].assigneeId,undefined);assert.equal(org.listTasks(ctx()).length,0);assert.deepEqual(await ai.preview(ctx(employee),input),r);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM ai_usage').get().n,1);assert.equal(store.db.prepare('SELECT cost_micros FROM ai_usage').get().cost_micros,90);});
test('demoted reviewer loses acceptance authority and review-stage reassignment cannot bypass return',t=>{const f=fixture(t),{owner,manager,employee,other,ctx,act,create,task,change}=f;const id=create(owner,{reviewerId:manager,reviewRequired:true});change(employee,id,'complete',{note:'交付'});const m=ctx(manager).member;act(owner,'member',{id:manager,name:m.name,role:'member',state:'active',departmentId:null},m.version);assert.equal(task(manager,id).permissions.review,false);denied(()=>change(manager,id,'approve'));change(employee,id,'request',{kind:'reassign',assigneeId:other,reason:'换人接手'});const r=f.org.detail(ctx(),id).requests[0];assert.throws(()=>change(owner,id,'resolve-request',{requestId:r.id,approved:true,note:''}),/退回/);});

test('online drafts isolate authors, accept incomplete input, detect conflicts and publish atomically',t=>{
 const {org,ctx,act,owner,employee,manager,store}=fixture(t),id=uid(),payload={content:{body:'尚未完成',startAt:'还没输完整'}};
 assert.equal(act(employee,'work-draft',{id,payload}).version,1);assert.equal(org.productivity.library(ctx()).drafts.length,0);assert.equal(org.productivity.draft(ctx(employee),id).payload.content.startAt,'还没输完整');denied(()=>org.productivity.draft(ctx(manager),id),404);
 assert.equal(act(employee,'work-draft',{id,payload}).version,1);act(employee,'work-draft',{id,payload:{content:{body:'第二台修改'}}},1);denied(()=>act(employee,'work-draft',{id,payload:{content:{body:'旧版本覆盖'}}},1),409);
 const taskId=uid(),publish={draftId:id,tasks:[{id:taskId,content:{body:'正式任务'},assignment:{assigneeId:employee},publish:true}]};denied(()=>act(owner,'publish-work-draft',publish,2),404);
 assert.throws(()=>act(employee,'publish-work-draft',{...publish,tasks:[{...publish.tasks[0],assignment:{assigneeId:manager}}]},2));assert.equal(org.productivity.draft(ctx(employee),id).version,2);assert.equal(org.getTask(taskId),undefined);
 const op={operationId:uid(),version:2,data:publish};org.mutate(ctx(employee),op,'publish-work-draft');org.mutate(ctx(employee),op,'publish-work-draft');assert.equal(org.listTasks(ctx(employee)).length,1);denied(()=>org.productivity.draft(ctx(employee),id),404);denied(()=>act(employee,'work-draft',{id,payload},2),409);assert.equal(store.exportAllData().organizationTables.org_work_drafts.length,0);
});
test('editing drafts require execution/edit rights and disappear when task access is removed',t=>{
 const {org,ctx,act,owner,employee,other,create,change}=fixture(t),taskId=create(owner,{visibility:'organization'}),id=uid();act(employee,'work-draft',{id,taskId,payload:{edit:{kind:'content',payload:{body:'编辑中'}}}});denied(()=>act(other,'work-draft',{id:uid(),taskId,payload:{edit:{}}}));change(owner,taskId,'assignment',taskAssignmentSchema.parse({assigneeId:other}));assert.equal(org.productivity.library(ctx(employee)).drafts.length,0);denied(()=>org.productivity.draft(ctx(employee),id),404);denied(()=>act(employee,'work-draft',{id,taskId,payload:{comment:'不能继续'}},1),404);
});
test('repeat generation rechecks permission, preserves workflow, deduplicates and skips missed slots',async t=>{
 const {org,ctx,act,owner,employee,store}=fixture(t),{shanghaiDay,occurrenceOnOrAfter}=await import('../server/organization-productivity.mjs'),today=shanghaiDay(),templateId=uid();act(owner,'template',{id:templateId,name:'每日检查',content:{body:'检查设备',scheduledDate:today,dueDate:today},assignment:{assigneeId:employee,acceptRequired:true,reviewRequired:true,reviewerId:owner}});assert.equal(org.productivity.library(ctx(employee)).templates.length,0);
 const repeatId=uid();act(owner,'repeat',{id:repeatId,templateId,rule:{frequency:'daily',startDate:today}});org.productivity.tick();org.productivity.tick();assert.equal(org.listTasks(ctx()).length,1);const first=org.listTasks(ctx())[0];assert.equal(first.source,'repeat');assert.equal(first.acceptRequired,true);assert.equal(first.reviewRequired,true);assert.equal(org.notifications(ctx(employee)).length,1);
 org.productivity.tick(Date.now()+3*86400000);assert.equal(org.listTasks(ctx()).length,2);assert.equal(store.db.prepare('SELECT COUNT(*) AS n FROM org_repeat_occurrences').get().n,2);
 const member=ctx(employee).member;act(owner,'member',{id:employee,name:member.name,role:member.role,state:'disabled',departmentId:null},member.version);org.productivity.tick(Date.now()+4*86400000);assert.equal(org.listTasks(ctx()).length,2);assert.equal(org.productivity.library(ctx()).repeats[0].state,'paused');assert.throws(()=>act(owner,'repeat-state',{id:repeatId,state:'active'},org.productivity.library(ctx()).repeats[0].version));
 assert.equal(occurrenceOnOrAfter({frequency:'monthly',interval:1,startDate:'2026-01-31'},'2026-02-01'),'2026-02-28');assert.equal(occurrenceOnOrAfter({frequency:'monthly',interval:1,startDate:'2026-01-31'},'2026-03-01'),'2026-03-31');assert.equal(occurrenceOnOrAfter({frequency:'monthly',interval:1,startDate:'2028-01-31'},'2028-02-01'),'2028-02-29');assert.equal(occurrenceOnOrAfter({frequency:'weekdays',interval:1,startDate:'2026-09-04'},'2026-09-05'),'2026-09-07');assert.equal(store.exportAllData().organizationTables.org_repeat_occurrences.length,2);
});
test('notification state explains opt-out, binding and acknowledgment',t=>{
 const {org,ctx,act,owner,employee,create}=fixture(t);create();const service=createOrganizationNotifications({org,wechat:{connected:()=>false},origin:'https://example.test'});assert.equal(service.list(ctx(employee))[0].deliveryState,'org_disabled');const c=ctx();act(owner,'settings',{name:c.org.name,shortName:c.org.short_name,state:'active',settings:{...c.org.settings,wechatEnabled:true}},c.org.version);assert.equal(service.list(ctx(employee))[0].deliveryState,'not_enabled');act(employee,'preferences',{wechat:true,mode:'immediate',quietStart:'00:00',quietEnd:'00:00'});assert.equal(service.list(ctx(employee))[0].deliveryState,'not_bound');const connected=createOrganizationNotifications({org,wechat:{connected:()=>true},origin:'https://example.test'});assert.equal(connected.list(ctx(employee))[0].deliveryState,'pending');act(employee,'ack',{id:org.notifications(ctx(employee))[0].id});assert.equal(connected.list(ctx(employee))[0].deliveryState,'acknowledged');
});
