import {createOrganizationExecution} from './organization-execution.mjs';
import {createOrganizationProductivity} from './organization-productivity.mjs';
import {randomUUID,createHash,createHmac} from 'node:crypto';
import {z} from 'zod';
import {orgId,orgDate,orgTime,orgSettingsSchema,memberPreferenceSchema,taskContentSchema,taskAssignmentSchema,taskDraftSchema} from './organization-schema.mjs';
export const orgFail=(message,status=400)=>Object.assign(new Error(message),{status});
const json=JSON.stringify,parse=JSON.parse,stamp=()=>new Date().toISOString(),hash=v=>createHash('sha256').update(v).digest('hex');
const version=z.number().int().positive(),name=z.string().trim().min(1).max(60),note=z.string().trim().max(3000),ids=z.array(orgId).max(100);
const wrap=z.object({operationId:orgId,version:version.optional(),data:z.unknown()}).strict();
export function createOrganizations({store,secret,origin}){
 const db=store.db;
 const getTask=id=>db.prepare('SELECT * FROM org_tasks WHERE id=?').get(id);
 function context(userId,orgId,{paused=false}={}){const org=db.prepare('SELECT * FROM organizations WHERE id=?').get(orgId),member=db.prepare("SELECT * FROM org_members WHERE org_id=? AND user_id=? AND state='active'").get(orgId,userId);if(!org||!member)throw orgFail('组织不存在或你已不再是成员',404);const admin=['owner','admin'].includes(member.role);if(org.state!=='active'&&!(paused&&admin))throw orgFail('组织已暂停',403);const scopes=db.prepare('SELECT s.*,EXISTS(SELECT 1 FROM org_scope_members m WHERE m.scope_id=s.id AND m.user_id=?) AS joined FROM org_scopes s WHERE org_id=? AND archived=0').all(userId,orgId);return {userId,orgId,org:{...org,settings:parse(org.settings)},member,admin,scopes};}
 const activeMember=(c,id)=>id&&db.prepare("SELECT * FROM org_members WHERE org_id=? AND user_id=? AND state='active'").get(c.orgId,id);
 const scopeMember=(scopeId,id)=>Boolean(db.prepare('SELECT 1 FROM org_scope_members WHERE scope_id=? AND user_id=?').get(scopeId,id));
 const manages=(c,t)=>c.admin||c.scopes.some(s=>s.lead_id===c.userId&&(s.id===t.project_id||s.id===t.department_id));
 function canRead(c,t){if(!t||t.org_id!==c.orgId)return false;if(t.status==='draft')return t.creator_id===c.userId;return manages(c,t)||t.assignee_id===c.userId||t.reviewer_id===c.userId||parse(t.collaborator_ids).includes(c.userId)||t.visibility==='organization'||(t.visibility==='project'&&scopeMember(t.project_id,c.userId))||(t.visibility==='department'&&scopeMember(t.department_id,c.userId));}
 function task(c,id){const t=getTask(id);if(!canRead(c,t))throw orgFail('任务不存在或权限已变更',404);return t;}
 function allowed(c,t){const manage=t.status!=='draft'&&manages(c,t),draft=t.status==='draft'&&t.creator_id===c.userId,execute=t.assignee_id===c.userId||parse(t.collaborator_ids).includes(c.userId),review=c.userId!==t.assignee_id&&!parse(t.collaborator_ids).includes(c.userId)&&manage;return {manage,edit:manage||draft,execute:execute||manage,submit:execute,review,draft,accept:t.assignee_id===c.userId};}
 function checkVersion(t,v){if(t.version!==v)throw orgFail('内容已被其他人更新，请刷新后重试',409);}
 function checkAssignment(c,a,{publishing=true}={}){
   for(const [id,kind] of [[a.projectId,'project'],[a.departmentId,'department']])if(id&&!c.scopes.some(s=>s.id===id&&s.kind===kind))throw orgFail('所属项目或部门已不可用');
   if(a.visibility==='project'&&!a.projectId||a.visibility==='department'&&!a.departmentId)throw orgFail('请先选择对应的项目或部门');
   const management=c.admin||c.scopes.some(s=>s.lead_id===c.userId&&(s.id===a.projectId||s.id===a.departmentId));
   if(!c.admin&&management&&(a.assigneeId!==c.userId||a.collaboratorIds.length||a.visibility!=='participants'))for(const sid of [a.projectId,a.departmentId].filter(Boolean))if(!c.scopes.some(s=>s.id===sid&&s.lead_id===c.userId))throw orgFail('跨范围分配需要同时拥有目标项目和部门的管理权限',403);
   if(!c.admin){for(const id of [a.projectId,a.departmentId].filter(Boolean))if(!scopeMember(id,c.userId)&&!c.scopes.some(s=>s.id===id&&s.lead_id===c.userId))throw orgFail('你不在所选项目或部门中',403);if(!management&&(a.assigneeId!==c.userId||a.collaboratorIds.length||a.visibility!=='participants'))throw orgFail('普通成员只能登记本人任务；参与范围由管理者调整',403);}
   for(const id of [a.assigneeId,a.reviewerId,...a.collaboratorIds].filter(Boolean)){if(!activeMember(c,id))throw orgFail('选中的成员已停用或离开组织');if(id!==a.reviewerId&&!c.admin){for(const sid of [a.projectId,a.departmentId].filter(Boolean))if(!scopeMember(sid,id))throw orgFail('只能给授权范围内的成员分配任务',403);}}
   if(a.reviewRequired&&(!a.reviewerId||a.reviewerId===a.assigneeId||a.collaboratorIds.includes(a.reviewerId)))throw orgFail('需要选择另一位管理者进行验收');
   if(a.reviewerId){const rc=context(a.reviewerId,c.orgId);if(!manages(rc,{project_id:a.projectId,department_id:a.departmentId}))throw orgFail('验收人需拥有该任务的管理权限');}
   if(publishing&&a.acceptRequired&&!a.assigneeId)throw orgFail('需要确认接收的任务必须有负责人');
 }
 function audit(c,action,detail){db.prepare('INSERT INTO org_audit VALUES (?,?,?,?,?,?)').run(randomUUID(),c.orgId,c.userId,action,json(detail),stamp());}
 function event(c,t,action,detail={}){db.prepare('INSERT INTO org_task_events VALUES (?,?,?,?,?,?,?)').run(randomUUID(),c.orgId,t.id,c.userId,action,json(detail),stamp());}
 function notify(c,t,kind,recipients,eventKey=randomUUID()) {for(const uid of new Set(recipients.filter(Boolean))){if(uid===c.userId||!activeMember(c,uid))continue;try{if(!canRead(context(uid,c.orgId),t))continue;}catch{continue;}db.prepare('INSERT OR IGNORE INTO org_notifications(id,org_id,task_id,recipient_id,actor_id,kind,event_key,created_at) VALUES (?,?,?,?,?,?,?,?)').run(randomUUID(),c.orgId,t.id,uid,c.userId,kind,eventKey,stamp());}}
 const managers=(c,t)=>db.prepare("SELECT user_id FROM org_members WHERE org_id=? AND state='active'").all(c.orgId).map(m=>m.user_id).filter(id=>manages(context(id,c.orgId),t));
 function render(c,t,full=false){const content={checklist:[],...parse(t.content)},pref=db.prepare('SELECT muted,snooze_until AS snoozeUntil,quadrant,focus_date AS focusDate FROM org_task_preferences WHERE task_id=? AND user_id=?').get(t.id,c.userId)||{};const result={id:t.id,orgId:t.org_id,version:t.version,creatorId:t.creator_id,assigneeId:t.assignee_id,reviewerId:t.reviewer_id,projectId:t.project_id,departmentId:t.department_id,collaboratorIds:parse(t.collaborator_ids),visibility:t.visibility,acceptRequired:!!t.accept_required,reviewRequired:!!t.review_required,status:t.status,source:t.source,acceptedAt:t.accepted_at,startedAt:t.started_at,submittedAt:t.submitted_at,completedAt:t.completed_at,archivedAt:t.archived_at,blockedReason:t.blocked_reason,completionNote:t.completion_note,reviewNote:t.review_note,createdAt:t.created_at,updatedAt:t.updated_at,originalDue:t.original_due,permissions:allowed(c,t),preference:pref,checklistProgress:execution.progress(t),content:{...content,...(!full?{body:undefined,checklist:undefined,acceptanceCriteria:undefined,title:content.title||content.body.split('\n')[0].slice(0,100)}:{})}};return result;}
 function candidates(c){return db.prepare('SELECT * FROM org_tasks WHERE org_id=? ORDER BY updated_at DESC').iterate(c.orgId);}
 function listTasks(c,query={}){const found=[];for(const t of candidates(c)){if(!canRead(c,t))continue;if(query.archived==='true'?!t.archived_at:!!t.archived_at)continue;const content=parse(t.content);if(query.mine==='true'&&t.assignee_id!==c.userId)continue;if(query.created==='true'&&t.creator_id!==c.userId)continue;if(query.status&&t.status!==query.status)continue;if(query.project&&t.project_id!==query.project)continue;if(query.department&&t.department_id!==query.department)continue;if(query.assignee&&t.assignee_id!==query.assignee)continue;if(query.source&&t.source!==query.source)continue;if(query.q&&!`${content.title}\n${content.body}`.toLowerCase().includes(String(query.q).slice(0,100).toLowerCase()))continue;found.push(render(c,t));}return found;}
 function list(userId){return db.prepare("SELECT o.*,m.name AS memberName,m.role,m.state AS memberState FROM organizations o JOIN org_members m ON m.org_id=o.id WHERE m.user_id=? AND m.state='active' ORDER BY o.created_at").all(userId).map(o=>({id:o.id,name:o.name,shortName:o.short_name,role:o.role,state:o.state,version:o.version,settings:parse(o.settings),transferTo:o.transfer_to}));}
 function home(c){const members=db.prepare('SELECT user_id AS id,name,role,state,department_id AS departmentId,version FROM org_members WHERE org_id=? ORDER BY joined_at').all(c.orgId);return {organization:list(c.userId).find(o=>o.id===c.orgId),me:{id:c.userId,role:c.member.role,preferences:parse(c.member.preferences)},admin:c.admin,scopes:c.scopes.map(s=>({id:s.id,name:s.name,kind:s.kind,leadId:s.lead_id,version:s.version,memberIds:db.prepare('SELECT user_id FROM org_scope_members WHERE scope_id=?').all(s.id).map(m=>m.user_id)})),members,canCreate:true};}
 function mutate(c,input,action){const w=wrap.parse(input),digest=hash(json({action,...w}));return store.transaction(()=>{c=context(c.userId,c.orgId,{paused:true});const prior=db.prepare('SELECT * FROM org_operations WHERE org_id=? AND user_id=? AND id=?').get(c.orgId,c.userId,w.operationId);if(prior){if(prior.request_hash!==digest)throw orgFail('这次操作编号已被使用',409);return {ok:true,replayed:true,...parse(prior.result)};}const result=action==='unused'?{}:perform(c,action,w);db.prepare('INSERT INTO org_operations VALUES (?,?,?,?,?,?)').run(c.orgId,c.userId,w.operationId,digest,json(result),stamp());return {ok:true,...result};});}
 function create(userId,input){const d=z.object({id:orgId,name,shortName:name.optional()}).strict().parse(input);return store.transaction(()=>{const old=db.prepare('SELECT id FROM organizations WHERE id=?').get(d.id);if(old){context(userId,d.id);return {id:d.id};}if(list(userId).filter(o=>o.role==='owner').length>=10)throw orgFail('每个账号最多创建 10 个组织');const u=db.prepare('SELECT * FROM users WHERE id=? AND verified_at IS NOT NULL').get(userId);if(!u)throw orgFail('请先验证邮箱',403);db.prepare('INSERT INTO organizations(id,name,short_name,settings,created_at) VALUES (?,?,?,?,?)').run(d.id,d.name,d.shortName||d.name,json(orgSettingsSchema.parse({})),stamp());db.prepare('INSERT INTO org_members(org_id,user_id,name,role,preferences,joined_at) VALUES (?,?,?,?,?,?)').run(d.id,userId,u.email.split('@')[0],'owner',json(memberPreferenceSchema.parse({})),stamp());return {id:d.id};});}
 const inviteCode=id=>createHmac('sha256',secret).update(`organization-invitation:${id}`).digest('base64url');
 function invitationLink(c,id){if(!c.admin)throw orgFail('没有邀请权限',403);const i=db.prepare("SELECT * FROM org_invitations WHERE id=? AND org_id=? AND state='pending'").get(id,c.orgId);if(!i)throw orgFail('邀请已失效',404);return `${origin}/#org-invite=${inviteCode(id)}`;}
 function join(userId,input){const {code}=z.object({code:z.string().regex(/^[A-Za-z0-9_-]{43}$/)}).strict().parse(input);return store.transaction(()=>{const i=db.prepare('SELECT * FROM org_invitations WHERE code_hash=?').get(hash(code)),u=db.prepare('SELECT * FROM users WHERE id=?').get(userId);if(!i||i.expires_at<stamp()||i.state!=='pending'||u.email!==i.email||!u.verified_at)throw orgFail('邀请已失效，或当前账号与受邀邮箱不一致');const inviter=context(i.created_by,i.org_id);if(!inviter.admin||(i.role==='admin'&&inviter.member.role!=='owner'))throw orgFail('邀请人的权限已变更，请联系组织重新邀请');if(i.department_id&&!inviter.scopes.some(s=>s.id===i.department_id))throw orgFail('邀请部门已变更，请重新邀请');const current=db.prepare('SELECT state FROM org_members WHERE org_id=? AND user_id=?').get(i.org_id,userId);if(current?.state==='active')throw orgFail('你已加入该组织');db.prepare("INSERT INTO org_members(org_id,user_id,name,role,department_id,preferences,joined_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(org_id,user_id) DO UPDATE SET state='active',role=excluded.role,department_id=excluded.department_id,version=org_members.version+1").run(i.org_id,userId,u.email.split('@')[0],i.role,i.department_id,json(memberPreferenceSchema.parse({})),stamp());if(i.department_id)db.prepare('INSERT OR IGNORE INTO org_scope_members VALUES (?,?)').run(i.department_id,userId);db.prepare("UPDATE org_invitations SET state='accepted' WHERE id=?").run(i.id);audit({...inviter,userId},'member.join',{userId});return {id:i.org_id};});}
 function perform(c,action,w){if(productivity.actions.has(action))return productivity.mutate(c,w,action);const d=w.data;
   if(action==='settings'){if(!c.admin)throw orgFail('需要组织管理员权限',403);checkVersion(c.org,w.version);const v=z.object({name,shortName:name,settings:orgSettingsSchema,state:z.enum(['active','paused'])}).strict().parse(d);db.prepare('UPDATE organizations SET name=?,short_name=?,settings=?,state=?,version=version+1 WHERE id=?').run(v.name,v.shortName,json(v.settings),v.state,c.orgId);if(v.state==='paused'||!v.settings.wechatEnabled)db.prepare("UPDATE org_notification_deliveries SET state='cancelled' WHERE org_id=? AND state IN ('pending','retry')").run(c.orgId);audit(c,'organization.settings',{settings:v.settings,state:v.state});return {};}
   if(action==='preferences'){const v=memberPreferenceSchema.parse(d);db.prepare('UPDATE org_members SET preferences=? WHERE org_id=? AND user_id=?').run(json(v),c.orgId,c.userId);return {};}
   if(action==='invite'){if(!c.admin)throw orgFail('需要组织管理员权限',403);const v=z.object({email:z.email().transform(s=>s.toLowerCase()),role:z.enum(['admin','member']).default('member'),departmentId:orgId.nullable().default(null)}).strict().parse(d);if(v.role==='admin'&&c.member.role!=='owner')throw orgFail('只有所有者能任命管理员',403);if(v.departmentId&&!c.scopes.some(s=>s.id===v.departmentId&&s.kind==='department'))throw orgFail('部门不存在');const id=randomUUID();db.prepare("UPDATE org_invitations SET state='revoked' WHERE org_id=? AND email=? AND state='pending'").run(c.orgId,v.email);db.prepare('INSERT INTO org_invitations(id,org_id,email,role,department_id,created_by,code_hash,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,c.orgId,v.email,v.role,v.departmentId,c.userId,hash(inviteCode(id)),new Date(Date.now()+7*86400000).toISOString(),stamp());audit(c,'member.invite',{email:v.email,role:v.role});return {invitationId:id};}
   if(action==='revoke-invitation'){if(!c.admin)throw orgFail('没有权限',403);const {id}=z.object({id:orgId}).strict().parse(d);db.prepare("UPDATE org_invitations SET state='revoked' WHERE id=? AND org_id=?").run(id,c.orgId);return {};}
   if(action==='member'){const v=z.object({id:orgId,name,role:z.enum(['admin','member','owner']),state:z.enum(['active','disabled','left']),departmentId:orgId.nullable()}).strict().parse(d),m=db.prepare('SELECT * FROM org_members WHERE org_id=? AND user_id=?').get(c.orgId,v.id);if(!m)throw orgFail('成员不存在',404);checkVersion(m,w.version);const self=v.id===c.userId;if(!c.admin&&!(self&&v.role===m.role&&v.departmentId===m.department_id&&(v.state==='left'||v.state===m.state)))throw orgFail('没有成员管理权限',403);if(m.role==='owner'&&(v.role!=='owner'||v.state!=='active'))throw orgFail('所有者需要先完成所有权转让');if(v.role==='owner'&&m.role!=='owner')throw orgFail('请使用所有权转让');if((m.role==='admin'||v.role==='admin')&&c.member.role!=='owner'&&!(self&&v.role===m.role&&v.state==='active'))throw orgFail('只有所有者可调整管理员',403);if(v.departmentId&&!c.scopes.some(s=>s.id===v.departmentId&&s.kind==='department'))throw orgFail('部门不存在');db.prepare('UPDATE org_members SET name=?,role=?,state=?,department_id=?,version=version+1 WHERE org_id=? AND user_id=?').run(v.name,v.role,v.state,v.departmentId,c.orgId,v.id);if(m.department_id!==v.departmentId){if(m.department_id)db.prepare('DELETE FROM org_scope_members WHERE scope_id=? AND user_id=?').run(m.department_id,v.id);if(v.departmentId)db.prepare('INSERT OR IGNORE INTO org_scope_members VALUES (?,?)').run(v.departmentId,v.id);}if(v.state!=='active'){db.prepare('DELETE FROM org_scope_members WHERE user_id=? AND scope_id IN (SELECT id FROM org_scopes WHERE org_id=?)').run(v.id,c.orgId);db.prepare("UPDATE org_notification_deliveries SET state='cancelled' WHERE org_id=? AND recipient_id=? AND state IN ('pending','retry')").run(c.orgId,v.id);db.prepare('UPDATE org_scopes SET lead_id=NULL,version=version+1 WHERE org_id=? AND lead_id=?').run(c.orgId,v.id);}audit(c,'member.change',{userId:v.id,from:{role:m.role,state:m.state,departmentId:m.department_id},to:v});return {};}
   if(action==='transfer'){const v=z.object({to:orgId.nullable(),accept:z.boolean().default(false)}).strict().parse(d);checkVersion(c.org,w.version);if(v.accept){if(c.org.transfer_to!==c.userId)throw orgFail('没有待接收的转让',403);db.prepare("UPDATE org_members SET role='admin',version=version+1 WHERE org_id=? AND role='owner'").run(c.orgId);db.prepare("UPDATE org_members SET role='owner',version=version+1 WHERE org_id=? AND user_id=?").run(c.orgId,c.userId);db.prepare('UPDATE organizations SET transfer_to=NULL,version=version+1 WHERE id=?').run(c.orgId);}else{if(c.member.role!=='owner')throw orgFail('只有所有者可发起转让',403);if(v.to&&(!activeMember(c,v.to)||v.to===c.userId))throw orgFail('请选择另一位正常成员');db.prepare('UPDATE organizations SET transfer_to=?,version=version+1 WHERE id=?').run(v.to,c.orgId);}audit(c,'organization.transfer',v);return {};}
   if(action==='scope'){if(!c.admin)throw orgFail('只有组织管理员可调整项目和部门',403);const v=z.object({id:orgId,name,kind:z.enum(['project','department']),leadId:orgId.nullable(),memberIds:ids,archived:z.boolean().default(false)}).strict().parse(d),old=db.prepare('SELECT * FROM org_scopes WHERE id=?').get(v.id);if(old&&old.org_id!==c.orgId)throw orgFail('项目不存在',404);if(old){checkVersion(old,w.version);if(old.kind!==v.kind)throw orgFail('不能改变部门或项目类型');}if(v.leadId&&!v.memberIds.includes(v.leadId))throw orgFail('负责人必须属于该项目或部门');for(const uid of v.memberIds)if(!activeMember(c,uid))throw orgFail('成员已停用');if(v.kind==='department')for(const uid of v.memberIds){const m=activeMember(c,uid);if(m.department_id&&m.department_id!==v.id)throw orgFail('成员已有部门，请先在成员页面调动');}db.prepare('INSERT INTO org_scopes(id,org_id,kind,name,lead_id,archived,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,lead_id=excluded.lead_id,archived=excluded.archived,version=org_scopes.version+1').run(v.id,c.orgId,v.kind,v.name,v.leadId,Number(v.archived),stamp());db.prepare('DELETE FROM org_scope_members WHERE scope_id=?').run(v.id);if(v.kind==='department')db.prepare('UPDATE org_members SET department_id=NULL,version=version+1 WHERE org_id=? AND department_id=?').run(c.orgId,v.id);for(const uid of v.archived?[]:v.memberIds){db.prepare('INSERT INTO org_scope_members VALUES (?,?)').run(v.id,uid);if(v.kind==='department')db.prepare('UPDATE org_members SET department_id=?,version=version+1 WHERE org_id=? AND user_id=?').run(v.id,c.orgId,uid);}audit(c,'scope.change',v);return {scopeId:v.id};}
   if(action==='create-tasks'){const v=z.object({tasks:z.array(taskDraftSchema).min(1).max(8),sourceId:orgId.optional(),sourceVersion:version.optional()}).strict().parse(d);if(v.sourceId){const privateEntry=store.forUser(c.userId).get(v.sourceId);if(!privateEntry||privateEntry.deletedAt)throw orgFail('私人来源不存在',404);checkVersion(privateEntry,v.sourceVersion);}for(const t of v.tasks){if(getTask(t.id))throw orgFail('任务编号已经使用',409);checkAssignment(c,t.assignment,{publishing:t.publish});const a=t.assignment,now=stamp();db.prepare('INSERT INTO org_tasks(id,org_id,creator_id,assignee_id,reviewer_id,project_id,department_id,collaborator_ids,visibility,accept_required,review_required,status,content,source,original_due,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(t.id,c.orgId,c.userId,a.assigneeId,a.reviewerId,a.projectId,a.departmentId,json(a.collaboratorIds),a.visibility,+a.acceptRequired,+a.reviewRequired,t.publish?'todo':'draft',json(t.content),v.sourceId?'personal':a.assigneeId&&a.assigneeId!==c.userId?'assigned':'self',t.content.dueDate,now,now);const created=getTask(t.id);event(c,created,t.publish?'published':'draft.created',{assigneeId:a.assigneeId,dueDate:t.content.dueDate});if(t.publish)notify(c,created,'assigned',[a.assigneeId,...a.collaboratorIds]);}return {taskIds:v.tasks.map(t=>t.id)};}
   if(action==='share'){const v=z.object({id:orgId,sourceId:orgId,sourceVersion:version,snapshot:taskContentSchema,visibility:z.enum(['recipients','project','department','organization']),scopeId:orgId.nullable(),recipients:ids,revoked:z.boolean().default(false)}).strict().parse(d),old=db.prepare('SELECT * FROM org_shares WHERE id=?').get(v.id);if(old&&(old.org_id!==c.orgId||old.owner_id!==c.userId))throw orgFail('分享不存在',404);if(old)checkVersion(old,w.version);const source=store.forUser(c.userId).get(v.sourceId);if(!source||source.deletedAt)throw orgFail('私人来源不存在',404);checkVersion(source,v.sourceVersion);if(['project','department'].includes(v.visibility)&&!c.scopes.some(s=>s.id===v.scopeId&&s.kind===v.visibility&&(s.joined||s.lead_id===c.userId)))throw orgFail('只能分享给自己所在的项目或部门');if(v.visibility==='recipients'&&!v.recipients.length)throw orgFail('请选择接收人');for(const id of v.recipients)if(!activeMember(c,id))throw orgFail('接收人已不在组织');db.prepare('INSERT INTO org_shares(id,org_id,owner_id,source_id,snapshot,recipients,visibility,scope_id,revoked_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET snapshot=excluded.snapshot,recipients=excluded.recipients,visibility=excluded.visibility,scope_id=excluded.scope_id,revoked_at=excluded.revoked_at,version=org_shares.version+1,updated_at=excluded.updated_at').run(v.id,c.orgId,c.userId,v.sourceId,json(v.snapshot),json(v.recipients),v.visibility,v.scopeId,v.revoked?stamp():null,stamp(),stamp());audit(c,'share.publish',{shareId:v.id,visibility:v.visibility});return {shareId:v.id};}
   if(action==='revoke-share'){const {id}=z.object({id:orgId}).strict().parse(d),s=db.prepare('SELECT * FROM org_shares WHERE id=? AND org_id=? AND owner_id=?').get(id,c.orgId,c.userId);if(!s)throw orgFail('分享不存在',404);checkVersion(s,w.version);db.prepare('UPDATE org_shares SET revoked_at=?,version=version+1 WHERE id=?').run(stamp(),id);return {};}
   if(action==='batch'){const v=z.object({items:z.array(z.object({id:orgId,version}).strict()).min(1).max(50),action:z.enum(['assign','archive','cancel']),assigneeId:orgId.nullable().optional(),reason:note.default('')}).strict().parse(d);for(const i of v.items){const t=task(c,i.id);checkVersion(t,i.version);if(!allowed(c,t).manage)throw orgFail('所选任务中有无权管理的内容',403);}for(const i of v.items){const t=task(c,i.id);if(v.action==='assign'){const a=assignmentOf(t);a.assigneeId=v.assigneeId??null;changeTask(c,t,'assignment',a);}else changeTask(c,t,v.action,{note:v.reason});}return {};}
   if(action==='ack'){const {id}=z.object({id:orgId}).strict().parse(d),n=db.prepare('SELECT * FROM org_notifications WHERE id=? AND org_id=? AND recipient_id=?').get(id,c.orgId,c.userId);if(!n)throw orgFail('通知不存在',404);if(n.task_id)task(c,n.task_id);db.prepare('UPDATE org_notifications SET acknowledged_at=COALESCE(acknowledged_at,?) WHERE id=?').run(stamp(),id);return {};}
   const v=z.object({id:orgId,payload:z.unknown()}).strict().parse(d),t=task(c,v.id);if(action!=='comment'&&action!=='task-preference')checkVersion(t,w.version);changeTask(c,t,action,v.payload);return {taskId:t.id};
 }
 function assignmentOf(t){return {assigneeId:t.assignee_id,reviewerId:t.reviewer_id,projectId:t.project_id,departmentId:t.department_id,collaboratorIds:parse(t.collaborator_ids),visibility:t.visibility,acceptRequired:!!t.accept_required,reviewRequired:!!t.review_required};}
 function changeTask(c,t,action,payload){const p=allowed(c,t),now=stamp();if(t.archived_at&&!['archive','task-preference'].includes(action))throw orgFail('请先恢复归档任务');let change={},detail={},recipients=[],kind=action;
   if(action==='comment'){if(t.status==='draft')throw orgFail('发布后才能讨论');const v=z.object({body:z.string().trim().min(1).max(3000),mentions:ids.default([])}).strict().parse(payload);for(const uid of v.mentions)if(!activeMember(c,uid)||!canRead(context(uid,c.orgId),t))throw orgFail('只能提及可查看任务的成员');db.prepare('INSERT INTO org_task_comments VALUES (?,?,?,?,?,?,?)').run(randomUUID(),c.orgId,t.id,c.userId,v.body,json(v.mentions),now);notify(c,t,'mentioned',v.mentions);return;}
   if(action==='task-preference'){const v=z.object({muted:z.boolean(),snoozeMinutes:z.union([z.literal(0),z.literal(15),z.literal(30),z.literal(60)]).default(0),quadrant:z.enum(['urgent-important','important','urgent','later']).nullable(),focusDate:orgDate.nullable()}).strict().parse(payload);db.prepare('INSERT INTO org_task_preferences VALUES (?,?,?,?,?,?) ON CONFLICT(task_id,user_id) DO UPDATE SET muted=excluded.muted,snooze_until=excluded.snooze_until,quadrant=excluded.quadrant,focus_date=excluded.focus_date').run(t.id,c.userId,+v.muted,v.snoozeMinutes?new Date(Date.now()+v.snoozeMinutes*60000).toISOString():null,v.quadrant,v.focusDate);return;}
   if(action==='content'){if(!p.edit)throw orgFail('正式任务的内容与期限由管理者调整，可提出变更申请',403);const content=taskContentSchema.parse({checklist:parse(t.content).checklist||[],...payload});execution.reconcile(t,content);change.content=json(content);detail={from:parse(t.content),to:content};}
   else if(['checklist-check','deliverable-add','deliverable-state'].includes(action)){detail=execution.apply(c,t,p,action,payload);}
   else if(action==='assignment'){if(!p.edit)throw orgFail('没有分配权限',403);const a=taskAssignmentSchema.parse(payload);checkAssignment(c,a);if(!c.admin&&!p.draft){const target={project_id:a.projectId,department_id:a.departmentId};if(!manages(c,target))throw orgFail('没有目标范围的管理权限',403);}change={assignee_id:a.assigneeId,reviewer_id:a.reviewerId,project_id:a.projectId,department_id:a.departmentId,collaborator_ids:json(a.collaboratorIds),visibility:a.visibility,accept_required:+a.acceptRequired,review_required:+a.reviewRequired};if(t.assignee_id!==a.assigneeId){change.accepted_at=null;recipients=[a.assigneeId];}detail={from:assignmentOf(t),to:a};if(['done','review','cancelled'].includes(t.status))throw orgFail('请先重新打开任务后调整分配');}
   else if(action==='request'){const v=z.object({kind:z.enum(['deadline','reassign','cancel','clarify']),reason:z.string().trim().min(1).max(3000),dueDate:orgDate.nullable().optional(),dueTime:orgTime.nullable().optional(),assigneeId:orgId.nullable().optional()}).strict().parse(payload);if(!p.execute)throw orgFail('只有任务执行者可提出申请',403);if(!['todo','doing','review'].includes(t.status))throw orgFail('当前状态不能提出申请');db.prepare('INSERT INTO org_task_requests(id,org_id,task_id,user_id,kind,proposal,reason,base_version,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(randomUUID(),c.orgId,t.id,c.userId,v.kind,json(v),v.reason,t.version,now);notify(c,t,'request',managers(c,t));return;}
   else if(action==='resolve-request'){if(!p.manage)throw orgFail('需要任务管理权限',403);const v=z.object({requestId:orgId,approved:z.boolean(),note}).strict().parse(payload),r=db.prepare("SELECT * FROM org_task_requests WHERE id=? AND task_id=? AND state='pending'").get(v.requestId,t.id);if(!r)throw orgFail('申请已处理',409);if(v.approved&&r.base_version!==t.version)throw orgFail('申请后任务已有更新，请退回并让成员重新提交',409);if(v.approved){const q=parse(r.proposal);if(q.kind==='deadline'){const content=taskContentSchema.parse({...parse(t.content),dueDate:q.dueDate??null,dueTime:q.dueTime??null});change.content=json(content);detail={from:parse(t.content).dueDate,to:content.dueDate};}if(q.kind==='reassign'){if(!['todo','doing'].includes(t.status))throw orgFail('请先退回或重新打开任务，再批准改派');const a={...assignmentOf(t),assigneeId:q.assigneeId??null};checkAssignment(c,a);change.assignee_id=a.assigneeId;change.accepted_at=null;recipients.push(a.assigneeId);}if(q.kind==='cancel')change.status='cancelled';}db.prepare('UPDATE org_task_requests SET state=?,resolved_by=?,resolution=? WHERE id=?').run(v.approved?'approved':'rejected',c.userId,v.note,r.id);detail={...detail,requestId:r.id,approved:v.approved,note:v.note};recipients.push(r.user_id);}
   else{const v=z.object({note:note.default('')}).strict().parse(payload??{});detail={note:v.note};
    if(action==='publish'){if(!p.draft)throw orgFail('只有草稿作者可以发布',403);checkAssignment(c,assignmentOf(t));change.status='todo';recipients=[t.assignee_id,...parse(t.collaborator_ids)];}
    else if(action==='accept'){if(!p.accept||!['todo','doing'].includes(t.status))throw orgFail('只有负责人可确认接收',403);change.accepted_at=t.accepted_at||now;}
    else if(action==='start'){if(!p.execute||!['todo','doing'].includes(t.status))throw orgFail('当前不能开始任务',403);if(!t.assignee_id||!activeMember(c,t.assignee_id))throw orgFail('请先分配给正常成员');if(t.accept_required&&!t.accepted_at)throw orgFail('负责人需要先确认接收');change={status:'doing',started_at:t.started_at||now};}
    else if(action==='complete'){if(!p.execute||!['todo','doing'].includes(t.status))throw orgFail('当前不能提交完成',403);if(c.userId!==t.assignee_id&&!parse(t.collaborator_ids).includes(c.userId))throw orgFail('请由负责人或协作者提交交付，管理者负责验收',403);if(!t.assignee_id||!activeMember(c,t.assignee_id))throw orgFail('请先交接给正常成员');if(t.accept_required&&!t.accepted_at)throw orgFail('负责人需要先确认接收');if(t.review_required&&!v.note)throw orgFail('请补充交付说明');execution.requireComplete(t);change={status:t.review_required?'review':'done',submitted_at:now,completed_at:t.review_required?null:now,completion_note:v.note,blocked_reason:''};recipients=t.review_required?[t.reviewer_id,...managers(c,t)]:[...managers(c,t),t.assignee_id];}
    else if(action==='approve'||action==='return'){if(!p.review||t.status!=='review')throw orgFail('当前不能验收，不能验收自己的交付',403);if(action==='return'&&!v.note)throw orgFail('请填写退回原因');if(action==='approve')execution.requireComplete(t);change={status:action==='approve'?'done':'doing',review_note:v.note,completed_at:action==='approve'?now:null};recipients=[t.assignee_id];}
    else if(action==='block'){if(!p.execute||!['todo','doing','review'].includes(t.status))throw orgFail('当前不能报告阻塞',403);change.blocked_reason=v.note;recipients=managers(c,t);}
    else if(action==='cancel'){if(!p.manage)throw orgFail('需要管理者批准取消',403);if(!v.note)throw orgFail('请说明取消原因');change={status:'cancelled',review_note:v.note};recipients=[t.assignee_id];}
    else if(action==='reopen'){if(!p.manage||!['done','cancelled','review'].includes(t.status))throw orgFail('只有管理者可重新打开',403);change={status:'todo',completed_at:null,submitted_at:null,review_note:v.note};recipients=[t.assignee_id];}
    else if(action==='archive'){if(!p.manage)throw orgFail('需要管理权限',403);if(!t.archived_at&&!['done','cancelled'].includes(t.status))throw orgFail('完成或取消后才可归档');change.archived_at=t.archived_at?null:now;}
    else throw orgFail('不支持的任务操作');
   }
   const keys=Object.keys(change);db.prepare(`UPDATE org_tasks SET ${keys.length?keys.map(k=>`${k}=?`).join(',')+',':''}version=version+1,updated_at=? WHERE id=?`).run(...keys.map(k=>change[k]),now,t.id);event(c,t,action,detail);const fresh=getTask(t.id);notify(c,fresh,kind,recipients);if(['done','cancelled'].includes(fresh.status)||fresh.archived_at)db.prepare("UPDATE org_notification_deliveries SET state='cancelled' WHERE org_id=? AND state IN ('pending','retry') AND id IN (SELECT delivery_id FROM org_notifications WHERE task_id=?)").run(c.orgId,t.id);
 }
 function detail(c,id){const t=task(c,id);return {task:render(c,t,true),checklist:execution.checklist(t),deliverables:execution.links(t),comments:db.prepare('SELECT id,user_id AS userId,body,mentions,created_at AS createdAt FROM org_task_comments WHERE task_id=? ORDER BY created_at LIMIT 1000').all(id).map(r=>({...r,mentions:parse(r.mentions)})),events:db.prepare('SELECT id,actor_id AS actorId,action,detail,created_at AS createdAt FROM org_task_events WHERE task_id=? ORDER BY created_at DESC LIMIT 200').all(id).map(r=>({...r,detail:parse(r.detail)})),requests:db.prepare('SELECT id,user_id AS userId,kind,reason,proposal,state,base_version AS baseVersion,resolution FROM org_task_requests WHERE task_id=? ORDER BY created_at DESC LIMIT 100').all(id).map(r=>({...r,proposal:parse(r.proposal)})),visibleMembers:db.prepare("SELECT user_id FROM org_members WHERE org_id=? AND state='active'").all(c.orgId).map(m=>m.user_id).filter(uid=>{try{return canRead(context(uid,c.orgId,{paused:true}),t);}catch{return false;}})};}
 function shares(c){return db.prepare('SELECT * FROM org_shares WHERE org_id=? AND revoked_at IS NULL ORDER BY updated_at DESC').all(c.orgId).filter(s=>activeMember(c,s.owner_id)&&(s.owner_id===c.userId||s.visibility==='organization'||s.visibility==='recipients'&&parse(s.recipients).includes(c.userId)||['project','department'].includes(s.visibility)&&scopeMember(s.scope_id,c.userId))).map(s=>({id:s.id,ownerId:s.owner_id,version:s.version,snapshot:parse(s.snapshot),visibility:s.visibility,scopeId:s.scope_id,recipients:parse(s.recipients),updatedAt:s.updated_at,...(s.owner_id===c.userId?{sourceId:s.source_id}:{})}));}
 function notifications(c){return db.prepare('SELECT n.*,d.state AS delivery_state FROM org_notifications n LEFT JOIN org_notification_deliveries d ON d.id=n.delivery_id WHERE n.org_id=? AND n.recipient_id=? ORDER BY n.created_at DESC LIMIT 300').all(c.orgId,c.userId).filter(n=>!n.task_id||canRead(c,getTask(n.task_id))).map(n=>({id:n.id,taskId:n.task_id,kind:n.kind,acknowledgedAt:n.acknowledged_at,createdAt:n.created_at,deliveryState:n.delivery_state||'pending'}));}
 function exportData(c){if(!c.admin&&!c.scopes.some(s=>s.lead_id===c.userId))throw orgFail('组织导出需要管理权限',403);const tasks=[];for(const t of candidates(c))if(t.status!=='draft'&&canRead(c,t)&&manages(c,t))tasks.push(detail(c,t.id));audit(c,'organization.export',{count:tasks.length});return {format:'joybeat-me-organization',schemaVersion:1,exportedAt:stamp(),organization:{id:c.orgId,name:c.org.name},tasks};}
 const execution=createOrganizationExecution({db,activeMember});
 const productivity=createOrganizationProductivity({store,context,task,allowed,checkAssignment,perform,audit});
 return {productivity,db,context,canRead,task,getTask,allowed,activeMember,render,list,home,listTasks,create,mutate,join,invitationLink,detail,shares,notifications,exportData,notify,managers};
}
