import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {aiPrompt,normalizeAiResult} from './ai.mjs';
import {entrySchema} from './schema.mjs';
import {taskContentSchema} from './organization-schema.mjs';
import {executionPlanPrompt,executionPlanSchema} from './execution-plan.mjs';
import {orgFail} from './organizations.mjs';
const stringify=JSON.stringify,day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function createOrganizationAi({store,org,config,fetchOverride=fetch}){
 const db=store.db;let active=0;
 function validate(c,feature){const fresh=org.context(c.userId,c.orgId);if(!fresh.org.settings[feature]||fresh.org.version!==c.org.version||fresh.member.version!==c.member.version)throw orgFail('组织权限或外部服务设置已有变化，请刷新后重试',403);return fresh;}
 function voiceContext(c){validate(c,'voiceEnabled');return {orgId:c.orgId,budgetYuan:c.org.settings.aiBudgetYuan,validate:()=>validate(c,'voiceEnabled')};}
 function validateTask(c,v){const fresh=validate(c,'aiEnabled');if(v.taskId){const t=org.task(fresh,v.taskId);if(!org.allowed(fresh,t).edit)throw orgFail('只有可编辑任务的成员能生成执行建议',403);if(t.version!==v.taskVersion)throw orgFail('任务已更新，请重新打开编辑后生成建议',409);if(!['draft','todo','doing'].includes(t.status)||t.archived_at)throw orgFail('请先退回或重新打开任务');}}
 async function preview(c,input){validate(c,'aiEnabled');if(!config?.enabled||!config?.apiKey)throw orgFail('AI 服务尚未配置',503);const v=z.object({id:z.uuid(),text:z.string().trim().min(1).max(8000),purpose:z.enum(['organize','execution']).default('organize'),taskId:z.uuid().optional(),taskVersion:z.number().int().positive().optional(),kind:z.enum(['auto','note','task','event']),content:taskContentSchema.optional(),manualFields:z.array(z.enum(Object.keys(taskContentSchema.shape))).max(20).default([]),consent:z.literal(true)}).strict().refine(v=>!!v.taskId===!!v.taskVersion,'任务编号与版本需同时提供').parse(input),digest=createHash('sha256').update(stringify(v)).digest('hex');validateTask(c,v);const previous=db.prepare('SELECT * FROM org_ai_previews WHERE id=?').get(v.id);if(previous){if(previous.org_id!==c.orgId||previous.user_id!==c.userId)throw orgFail('整理记录不存在',404);if(previous.request_hash!==digest)throw orgFail('输入已变化，请重新整理',409);if(previous.state==='done'&&previous.created_at>Date.now()-600000)return JSON.parse(previous.result);throw orgFail('上次整理未完成或已过期，请重新整理',409);}if(active>=2)throw orgFail('AI 正忙，请稍后再试',429);
 const messages=[{role:'system',content:v.purpose==='execution'?executionPlanPrompt:aiPrompt+'\n本次是组织草稿：不匹配人员，不作权限或验收决定。manualFields 指定的字段由用户手填，优先保留；若发现矛盾仅在 advice 中提示。'},{role:'user',content:stringify({referenceTime:new Date().toISOString(),timezone:'Asia/Shanghai',requestedKind:v.kind,text:v.text,content:v.content,manualFields:v.manualFields})}],reserve=Math.ceil(Buffer.byteLength(stringify(messages))*.15+4500),usageId=randomUUID(),today=day(),month=today.slice(0,7);
 store.transaction(()=>{const global=db.prepare('SELECT (SELECT COALESCE(SUM(cost_micros),0) FROM ai_usage WHERE month_key=?)+(SELECT COALESCE(SUM(cost_micros),0) FROM voice_usage WHERE month_key=?) AS n').get(month,month).n,spent=db.prepare('SELECT (SELECT COALESCE(SUM(cost_micros),0) FROM ai_usage WHERE month_key=? AND org_id=?)+(SELECT COALESCE(SUM(cost_micros),0) FROM voice_usage WHERE month_key=? AND org_id=?) AS n').get(month,c.orgId,month,c.orgId).n,count=db.prepare('SELECT COUNT(*) AS n FROM ai_usage WHERE user_id=? AND day_key=?').get(c.userId,today).n,all=db.prepare('SELECT COUNT(*) AS n FROM ai_usage WHERE day_key=?').get(today).n;if(global+reserve>Math.min(20,config.monthlyBudgetYuan??20)*1e6||spent+reserve>c.org.settings.aiBudgetYuan*1e6||count>=(config.perUserDailyLimit??100)||all>=(config.globalDailyLimit??2000))throw orgFail('整理额度已用完，仍可手动发布',429);db.prepare('INSERT INTO ai_usage(id,job_id,user_id,day_key,month_key,cost_micros,created_at,org_id) VALUES (?,?,?,?,?,?,?,?)').run(usageId,v.id,c.userId,today,month,reserve,new Date().toISOString(),c.orgId);db.prepare("INSERT INTO org_ai_previews(id,org_id,user_id,request_hash,state,created_at) VALUES (?,?,?,?,'running',?)").run(v.id,c.orgId,c.userId,digest,Date.now());});active++;
 try{const response=await fetchOverride('https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',{method:'POST',redirect:'error',signal:AbortSignal.timeout(45000),headers:{'Content-Type':'application/json',Authorization:`Bearer ${config.apiKey}`},body:stringify({model:'qwen-flash',messages,enable_thinking:false,stream:false,temperature:.1,max_tokens:3000,response_format:{type:'json_object'}})});if(!response.ok)throw orgFail('AI 暂时不可用，输入内容仍在',503);const raw=await response.text();if(raw.length>100000)throw orgFail('AI 返回过长');const answer=JSON.parse(raw);validateTask(c,v);if(answer.choices?.[0]?.finish_reason!=='stop')throw orgFail('AI 返回不完整，请重试');const u=answer.usage;if(Number.isInteger(u?.prompt_tokens)&&u.prompt_tokens>=0&&Number.isInteger(u?.completion_tokens)&&u.completion_tokens>=0)db.prepare('UPDATE ai_usage SET prompt_tokens=?,completion_tokens=?,cost_micros=? WHERE id=?').run(u.prompt_tokens,u.completion_tokens,Math.ceil(u.prompt_tokens*.15+u.completion_tokens*1.5),usageId);const parsed=JSON.parse(answer.choices[0].message.content);let result;if(v.purpose==='execution'){result={plan:executionPlanSchema.parse(parsed),taskId:v.taskId||null,taskVersion:v.taskVersion||null};}else{const original=entrySchema.parse({id:v.id,kind:v.kind==='auto'?'note':v.kind,body:v.text}),normalized=normalizeAiResult(parsed,original,v.kind,Date.now());result={items:normalized.entries.map(e=>taskContentSchema.parse(Object.fromEntries(Object.keys(taskContentSchema.shape).filter(k=>k in e).map(k=>[k,e[k]])))),advice:normalized.advice};}db.prepare("UPDATE org_ai_previews SET state='done',result=? WHERE id=?").run(stringify(result),v.id);return result;
 }catch(e){db.prepare("UPDATE org_ai_previews SET state='failed',result=NULL,error='整理未完成' WHERE id=?").run(v.id);throw e.status?e:orgFail('整理未完成，原文仍在，可以手动发布',503);}finally{active--;}}
 function cleanup(){db.prepare('DELETE FROM org_ai_previews WHERE created_at<?').run(Date.now()-86400000);}
 return {preview,voiceContext,cleanup};
}
