import React,{useEffect,useRef,useState} from 'react';
import {Mail,LogOut,ShieldCheck,Monitor,Smartphone,Bell,Download,Upload,MessageCircle,ExternalLink,KeyRound} from 'lucide-react';
import {AiSettings} from './AiTools';
import {finishLogout} from './AuthGate';
import {dateLabel,timeLabel} from './model';
const deliveryNames={pending:'等待发送',sending:'正在发送',retry:'稍后重试',queued:'已提交，等待回执',delivered:'平台报告已投递',failed:'发送失败',unknown:'结果未确认',cancelled:'已取消'};

export function AccountSettings({ai,workspace,onClose,notify,Modal}){
  const [devices,setDevices]=useState([]),[wechat,setWechat]=useState(null),[system,setSystem]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[token,setToken]=useState(''),[consent,setConsent]=useState(false),[revoke,setRevoke]=useState(null),[importData,setImportData]=useState(null),[oldPassword,setOldPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[passwordConfirm,setPasswordConfirm]=useState(''),[logoutConfirm,setLogoutConfirm]=useState(false);
  const fileRef=useRef(),user=workspace.session?.user,current=devices.find(d=>d.current);
  async function load(){const values=await Promise.all([workspace.api('/api/devices'),workspace.api('/api/wechat'),workspace.api('/api/system')]);setDevices(values[0].devices);setWechat(values[1]);setSystem(values[2]);}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  useEffect(()=>{let alive=true;const timer=setInterval(()=>{if(document.visibilityState==='visible')workspace.api('/api/wechat').then(value=>{if(alive)setWechat(value);}).catch(()=>{});},4000);return()=>{alive=false;clearInterval(timer);};},[workspace.api]);
  async function run(action){setBusy(true);setError('');try{await action();await load();await workspace.sync();}catch(e){setError(e.message);await load().catch(()=>{});await workspace.sync();}finally{setBusy(false);}}
  async function enablePush(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('此浏览器暂不支持推送；iPhone 需先添加到主屏幕');if(!workspace.session?.pushPublicKey)throw new Error('浏览器提醒尚未配置');if(await Notification.requestPermission()!=='granted')throw new Error('请在浏览器设置中允许通知');const registration=await navigator.serviceWorker.getRegistration();if(!registration)throw new Error('离线组件尚未就绪，请刷新后重试');const key=workspace.session.pushPublicKey,binary=atob((key+'='.repeat((4-key.length%4)%4)).replace(/-/g,'+').replace(/_/g,'/'));const sub=await registration.pushManager.getSubscription()??await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(binary,c=>c.charCodeAt(0))});await workspace.api('/api/push/subscribe',{method:'POST',body:JSON.stringify(sub.toJSON())});notify('本机提醒已开启，请发送测试通知');}
  async function logout(){setBusy(true);setError('');try{if(workspace.state.queue.length)throw new Error('还有内容待上传，请联网同步后再退出');await workspace.api('/api/auth/logout',{method:'POST',body:'{}'});await workspace.stop();await finishLogout(user);}catch(e){setError(e.message);setBusy(false);}}
  return <Modal title="账号与设置" onClose={onClose} wide><div className="settings-body"><section className="account-summary"><div><Mail size={21}/><strong>{user?.email??'正在连接'}</strong><span className="pill green">{user?.emailVerified?'邮箱已验证':'正在确认'}</span></div><button className="button secondary" disabled={busy||!user} onClick={()=>{if(workspace.state.draft?.trim()||workspace.state.editorDraft)setLogoutConfirm(true);else logout();}}><LogOut size={15}/>退出登录</button>{logoutConfirm&&<div className="confirmation"><p>本机还有未提交的草稿。退出会清除这台浏览器的离线副本和草稿。</p><div className="button-row"><button className="button secondary" onClick={()=>setLogoutConfirm(false)}>返回，先保存草稿</button><button className="button danger" onClick={logout} disabled={busy||workspace.state.queue.length>0}>放弃草稿并退出</button></div></div>}</section>
  {error&&<p className="form-error" role="alert">{error}</p>}
  <AiSettings ai={ai} notify={notify}/>
  <section className="wechat-settings"><div className="settings-section-title"><MessageCircle size={19}/><h3>微信提醒</h3><span className={`pill ${wechat?.connected?'green':''}`}>{wechat?.connected?'已连接':'未连接'}</span></div><p className="muted">通过 PushPlus 将你选择的记录、日程和待办发送到微信。设置提醒时间后，即使网页关闭，也由服务器按时提交。</p>
  <ol className="wechat-steps"><li>打开 <a href="https://www.pushplus.plus/" target="_blank" rel="noreferrer">PushPlus <ExternalLink size={12}/></a>，用微信登录、关注公众号，并按平台要求完成实名认证。</li><li>复制“一对一推送”的通知令牌，粘贴到下方连接。</li><li>发送测试，确认微信收到；再为需要的记录勾选微信提醒。</li></ol>
  {wechat?.available&&<><label className="setting-label">{wechat.connected?'更换通知令牌（选填）':'通知令牌'}<input type="password" autoComplete="off" aria-label="微信通知令牌" value={token} onChange={e=>setToken(e.target.value.trim())} placeholder="粘贴 PushPlus Token" maxLength={128}/></label><label className="consent-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>我同意将主动推送或勾选微信提醒的内容，经 PushPlus 转发到我的微信。</label><div className="button-row"><button className="button primary" disabled={busy||!consent||!token} onClick={()=>run(async()=>{await workspace.api('/api/wechat/binding',{method:'POST',body:JSON.stringify({token,consent:true})});setToken('');setConsent(false);notify('微信提醒已连接，请发送测试确认');})}>连接微信</button><button className="button secondary" disabled={busy||!wechat.connected} onClick={()=>run(async()=>{const r=await workspace.api('/api/wechat/send',{method:'POST',body:'{}'});notify(r.message);})}>发送微信测试</button>{wechat.connected&&<button className="text-button danger-text" disabled={busy} onClick={()=>run(async()=>{await workspace.api('/api/wechat/binding',{method:'DELETE',body:'{}'});notify('微信提醒已断开，待发送提醒已取消');})}>断开连接</button>}</div></>}
  <p className="settings-footnote">通知正文最多展示前 2,000 个字符，附带需要登录的原文链接。通知服务的额度和送达情况以 PushPlus 为准。</p>{wechat?.deliveries?.length>0&&<div className="delivery-list"><strong>最近的推送</strong>{wechat.deliveries.slice(0,5).map(item=><div key={item.id}><span>{item.mode==='test'?'连接测试':workspace.state.entries.find(e=>e.id===item.entryId)?.title||'记录提醒'}</span><small>{dateLabel(item.createdAt)} {timeLabel(item.createdAt)}</small><span className={`pill ${item.state==='delivered'?'green':''}`}>{deliveryNames[item.state]??item.state}</span>{item.response&&<span className="pill green">{item.response==='done'?'本人已完成':item.response==='snoozed'?'本人已延后':'本人已知晓'}</span>}{item.error&&<p>{item.error}</p>}</div>)}</div>}</section>
  <section><div className="settings-section-title"><Bell size={18}/><h3>浏览器提醒</h3><span className={`pill ${current?.notifications?'green':''}`}>{current?.notifications?'已开启':'未开启'}</span></div><p className="muted">也可以在这台设备接收浏览器通知。请在锁屏状态下验证实际送达。</p><div className="button-row"><button className="button secondary" disabled={busy} onClick={()=>run(enablePush)}>开启本机提醒</button><button className="button secondary" disabled={busy||!current?.notifications} onClick={()=>run(async()=>{const result=await workspace.api('/api/push/test',{method:'POST',body:'{}'});notify(result.message);})}>发送测试</button>{current?.notifications&&<button className="text-button" onClick={()=>run(async()=>{await workspace.api('/api/push/unsubscribe',{method:'POST',body:'{}'});await (await (await navigator.serviceWorker.getRegistration())?.pushManager.getSubscription())?.unsubscribe();})}>关闭本机提醒</button>}</div></section>
  <section><div className="settings-section-title"><ShieldCheck size={18}/><h3>登录设备</h3></div><p className="muted">这里只显示当前账号的登录。可以结束其他设备的登录状态。</p><div className="device-list">{devices.map(device=><div className="device-row" key={device.id}>{/手机|iPhone/i.test(device.name)?<Smartphone size={20}/>:<Monitor size={20}/>}<div><strong>{device.name} {device.current&&<span className="tiny-label">当前设备</span>}</strong><small>{device.active?`最近访问 ${dateLabel(device.lastSeen??device.createdAt)}`:'已退出'}</small></div>{device.active&&!device.current&&<button className="text-button danger-text" onClick={()=>setRevoke(device)}>退出此设备</button>}</div>)}</div>{revoke&&<div className="confirmation"><p>结束「{revoke.name}」的登录？该设备需要重新输入账号密码。已经下载的离线内容无法远程收回。</p><div className="button-row"><button className="button danger" disabled={busy} onClick={()=>run(async()=>{await workspace.api(`/api/devices/${revoke.id}`,{method:'PATCH',body:JSON.stringify({revoke:true})});setRevoke(null);})}>确认退出</button><button className="button secondary" onClick={()=>setRevoke(null)}>取消</button></div></div>}</section>
  <section><div className="settings-section-title"><Download size={18}/><h3>我的数据与备份</h3></div><p className="muted">导出只包含当前账号的内容。导入保留现有记录，同编号内容会跳过。</p><div className="button-row"><a className="button secondary" href={`/api/export?account=${encodeURIComponent(user?.id??'')}`} download><Download size={15}/>导出我的数据</a><button className="button secondary" disabled={busy||workspace.state.queue.length>0} onClick={()=>fileRef.current.click()}><Upload size={15}/>导入备份</button><input ref={fileRef} className="hidden" type="file" accept="application/json,.json" onChange={async e=>{try{const file=e.target.files?.[0];if(!file)return;if(file.size>10*1024*1024)throw new Error('文件不能超过 10 MB');const data=JSON.parse(await file.text());if(data.format!=='joybeat-me'||!Array.isArray(data.entries))throw new Error('请选择从账号中导出的 Me 备份');setImportData(data);}catch(e){setError(e.message);}e.target.value='';}}/></div>{importData&&<div className="confirmation"><p>将 {importData.entries.length} 条内容导入当前账号？已有内容会保留。</p><button className="button primary" disabled={busy} onClick={()=>run(async()=>{const r=await workspace.api('/api/import',{method:'POST',body:JSON.stringify(importData)});setImportData(null);notify(`已导入 ${r.imported} 条，跳过 ${r.skipped} 条`);})}>确认导入</button><button className="text-button" onClick={()=>setImportData(null)}>取消</button></div>}<p className="settings-footnote">{system?.lastBackup?`最近服务器备份：${dateLabel(system.lastBackup.at)} ${timeLabel(system.lastBackup.at)}`:'备份状态待更新'} · 本机待上传 {workspace.state.queue.length} 项</p></section>
  <section><details><summary className="settings-section-title"><KeyRound size={18}/><h3>修改密码</h3></summary><form className="password-change" onSubmit={e=>{e.preventDefault();run(async()=>{if(newPassword!==passwordConfirm)throw new Error('两次新密码不一致');if(workspace.state.queue.length||workspace.state.draft?.trim()||workspace.state.editorDraft)throw new Error('请先保存草稿并完成同步，再修改密码');await workspace.api('/api/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:oldPassword,password:newPassword})});await workspace.stop();await finishLogout(user);});}}><label>当前密码<input type="password" autoComplete="current-password" required maxLength={128} value={oldPassword} onChange={e=>setOldPassword(e.target.value)}/></label><label>新密码<input type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>确认新密码<input type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={passwordConfirm} onChange={e=>setPasswordConfirm(e.target.value)}/></label><p className="muted">修改后，所有设备都需要重新登录。</p><button className="button primary" disabled={busy}>更新密码</button></form></details></section>
  <section className="about-section"><div className="brand small">me<span>.</span></div><div><strong>一个留给自己的空间</strong><p>服务器到期：2027 年 6 月 16 日 · 到期前迁移</p><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">京ICP备2026054579号</a></div><span className="quiet">v3.0</span></section></div></Modal>;
}
