import React,{useEffect,useRef,useState} from 'react';
import {Mail,LockKeyhole,ArrowRight,LoaderCircle,ShieldCheck,NotebookPen,CalendarDays} from 'lucide-react';
import {clearUserState} from './storage';

export function notifyAuthChange(){const channel=new BroadcastChannel('me-account-auth');channel.postMessage('changed');channel.close();window.dispatchEvent(new Event('me-auth-required'));}
export async function finishLogout(user){const userId=user.id;await clearUserState(userId);localStorage.removeItem('joybeat-board-layout-v2:'+userId);if(user.role==='owner')localStorage.removeItem('joybeat-board-layout-v1');sessionStorage.removeItem('me-active-account');notifyAuthChange();}
export function AuthGate({children}){
  const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[config,setConfig]=useState({mailConfigured:false,registration:'open'}),[error,setError]=useState('');
  async function check(){try{const response=await fetch('/api/auth/status'),data=await response.json();if(!response.ok)throw new Error('暂时无法连接服务器');setConfig(data);setUser(data.authenticated?data.user:null);if(data.authenticated)sessionStorage.setItem('me-active-account',JSON.stringify({user:data.user,at:Date.now()}));else sessionStorage.removeItem('me-active-account');setError('');}catch{let cached;try{cached=JSON.parse(sessionStorage.getItem('me-active-account'));}catch{}if(cached&&Date.now()-cached.at<12*3600000)setUser(cached.user);else{setUser(null);setError('暂时无法连接，请联网后登录。');}}finally{setLoading(false);}}
  useEffect(()=>{check();const bus=new BroadcastChannel('me-account-auth');const changed=()=>{sessionStorage.removeItem('me-active-account');setUser(null);check();};bus.onmessage=changed;window.addEventListener('me-auth-required',changed);window.addEventListener('online',check);return()=>{bus.close();window.removeEventListener('me-auth-required',changed);window.removeEventListener('online',check);};},[]);
  function loggedIn(data){sessionStorage.setItem('me-active-account',JSON.stringify({user:data.user,at:Date.now()}));sessionStorage.removeItem('me-invite-code');setUser(data.user);const bus=new BroadcastChannel('me-account-auth');bus.postMessage('changed');bus.close();}
  if(loading)return <main className="auth-loading"><span className="brand">me<span>.</span></span><LoaderCircle className="spin" size={22}/></main>;
  if(user)return children(user);
  return <LoginForm config={config} connectionError={error} onLogin={loggedIn}/>;
}

function LoginForm({config,connectionError,onLogin}){
  const initialInvite=useRef(new URLSearchParams(location.hash.slice(1)).get('invite')||sessionStorage.getItem('me-invite-code')||'');
  const [mode,setMode]=useState(initialInvite.current?'register':'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[code,setCode]=useState(''),[invite,setInvite]=useState(initialInvite.current),[busy,setBusy]=useState(false),[sending,setSending]=useState(false),[cooldown,setCooldown]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{if(initialInvite.current){sessionStorage.setItem('me-invite-code',initialInvite.current);history.replaceState(null,'',location.pathname+location.search);}if('serviceWorker'in navigator&&import.meta.env.PROD)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
  useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(c=>c-1),1000);return()=>clearTimeout(timer);},[cooldown]);
  async function request(path,body){const response=await fetch('/api/auth/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'操作未完成');return data;}
  function changeMode(next){setMode(next);setError('');setMessage('');setPassword('');setConfirm('');setCode('');}
  async function sendCode(){setError('');setMessage('');setSending(true);try{const result=await request('email-code',{email:email.trim(),purpose:mode==='reset'?'reset':'register',...(invite?{inviteCode:invite}:{})});setMessage(result.message);setCooldown(60);}catch(e){setError(e.message);}finally{setSending(false);}}
  async function submit(event){event.preventDefault();setError('');setMessage('');if(mode!=='login'&&password!==confirm){setError('两次输入的密码不一致');return;}setBusy(true);try{
    const path=mode==='reset'?'reset-password':mode,body={email:email.trim(),password,...(mode!=='login'?{code}:{}),...(mode==='register'&&invite?{inviteCode:invite}:{})};
    const data=await request(path,body);if(mode==='reset'){changeMode('login');setMessage('密码已更新，请登录。');}else onLogin(data);
  }catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="auth-page"><section className="auth-story"><div className="brand">me<span>.</span></div><div className="auth-story-content"><span className="eyebrow">留一点空间，给自己</span><h1>把想法留下，<br/>把日子过好。</h1><p>随手记录，慢慢整理。<br/>让每一个值得的念头，都有下一步。</p><div className="auth-features"><span><NotebookPen size={17}/>留住灵感</span><span><CalendarDays size={17}/>安排日常</span><span><ShieldCheck size={17}/>自己的空间</span></div></div><span className="auth-decoration" aria-hidden="true">✳</span></section><section className="auth-form-side"><div className="auth-form-wrap"><span className="auth-kicker">YOUR PERSONAL SPACE</span><h2>{mode==='login'?'欢迎回来。':mode==='register'?'从这里开始。':'重新设置密码。'}</h2><p className="muted">{mode==='login'?'登录后，继续你的记录与计划。':mode==='register'?'每个账号都有独立的记录、待办和提醒。':'验证邮箱后，为账号设置一个新密码。'}</p>{mode!=='reset'&&<div className="auth-tabs"><button className={mode==='login'?'selected':''} onClick={()=>changeMode('login')}>登录</button><button className={mode==='register'?'selected':''} onClick={()=>changeMode('register')}>注册账号</button></div>}
  <form onSubmit={submit} className="auth-form"><label>邮箱<div className="auth-input"><Mail size={17}/><input type="email" autoComplete="username" aria-label="邮箱" required maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="你的邮箱地址"/></div></label>{mode==='register'&&(config.registration==='invite'||invite)&&<label>邀请码<input aria-label="邀请码" value={invite} onChange={e=>setInvite(e.target.value)} maxLength={128} required/></label>}{mode!=='login'&&<label>邮箱验证码<div className="auth-code"><input aria-label="邮箱验证码" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="6 位验证码"/><button type="button" className="button secondary" disabled={!config.mailConfigured||sending||cooldown>0||!email.includes('@')} onClick={sendCode}>{sending?'正在发送':cooldown?`${cooldown} 秒后重发`:'发送验证码'}</button></div></label>}
  <label>{mode==='reset'?'新密码':'密码'}<div className="auth-input"><LockKeyhole size={17}/><input type="password" aria-label={mode==='reset'?'新密码':'密码'} autoComplete={mode==='login'?'current-password':'new-password'} minLength={mode==='login'?undefined:10} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'输入密码':'至少 10 个字符'}/></div></label>{mode!=='login'&&<label>确认密码<input type="password" aria-label="确认密码" autoComplete="new-password" minLength={10} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="再输入一次密码"/></label>}
  {(error||connectionError)&&<p className="form-error" role="alert">{error||connectionError}</p>}{message&&<p className="auth-success" role="status">{message}</p>}{mode!=='login'&&!config.mailConfigured&&<p className="auth-service-note">验证码发送服务正在准备中，暂时无法注册或找回密码。</p>}<button className="button primary auth-submit" disabled={busy||(mode!=='login'&&!config.mailConfigured)}>{busy?<LoaderCircle className="spin" size={17}/>:<ArrowRight size={17}/>}<span>{mode==='login'?'登录我的空间':mode==='register'?'验证邮箱并注册':'更新密码'}</span></button></form>
  <div className="auth-links"><button className="text-button" onClick={()=>changeMode(mode==='reset'?'login':'reset')}>{mode==='reset'?'返回登录':'忘记密码？'}</button><span>记录仅对你的账号可见</span></div></div><footer className="auth-footer"><span>me. 留一点空间，给自己。</span><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">京ICP备2026054579号</a></footer></section></main>;
}
