import React,{useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,Trash2,Plus,Sparkles} from 'lucide-react';
import {appendPlanSteps} from './execution-model';
export function ChecklistFields({items=[],onChange,disabled=false}){
 const move=(i,d)=>{const next=[...items];[next[i],next[i+d]]=[next[i+d],next[i]];onChange(next);};
 return <div className="org-checklist-editor">{items.map((item,i)=><div key={item.id} className="org-step-edit"><span className="org-step-number">{i+1}</span><label className="org-step-text"><span className="sr-only">步骤 {i+1}</span><input disabled={disabled} maxLength={300} value={item.text} placeholder="一个可以确认完成的动作" onChange={e=>onChange(items.map((s,k)=>k===i?{...s,text:e.target.value}:s))}/></label><div className="org-step-controls"><label className="check-label"><input disabled={disabled} type="checkbox" checked={item.required} onChange={e=>onChange(items.map((s,k)=>k===i?{...s,required:e.target.checked}:s))}/>必做</label><button type="button" disabled={disabled||i===0} className="icon-button" aria-label={'上移步骤 '+(i+1)} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button type="button" disabled={disabled||i===items.length-1} className="icon-button" aria-label={'下移步骤 '+(i+1)} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button type="button" disabled={disabled} className="icon-button" aria-label={'删除步骤 '+(i+1)} onClick={()=>onChange(items.filter((_,k)=>k!==i))}><Trash2 size={15}/></button></div></div>)}<button type="button" className="button secondary" disabled={disabled||items.length>=40} onClick={()=>onChange([...items,{id:crypto.randomUUID(),text:'',required:true}])}><Plus size={15}/>添加步骤</button>{items.length>0&&<p className="org-hint">必做项完成后才能提交任务。修改已完成步骤的内容或必做设置后，该步骤需要重新确认。</p>}</div>;
}
export function ExecutionPlanEditor({value,onChange,home,api,taskId,taskVersion,onBusy}){
 const [plan,setPlan]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState([]),[useCriteria,setUseCriteria]=useState(false);const current=useRef(value),alive=useRef(true);current.current=value;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function generate(){setBusy(true);onBusy?.(true);setError('');const basis=JSON.stringify(value);try{const result=await api('/ai',{method:'POST',body:JSON.stringify({id:crypto.randomUUID(),purpose:'execution',kind:value.kind,text:value.body,content:value,consent:true,...(taskId?{taskId,taskVersion}:{})})});if(!alive.current)return;if(JSON.stringify(current.current)!==basis)throw new Error('输入已经变化，请基于最新内容重新生成');setPlan(result.plan);setSelected(result.plan.steps.map((_,i)=>i));setUseCriteria(!value.acceptanceCriteria?.trim());}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current){setBusy(false);onBusy?.(false);}}}
 function apply(){try{onChange({...value,checklist:appendPlanSteps(value.checklist||[],plan.steps.filter((_,i)=>selected.includes(i))),acceptanceCriteria:useCriteria?plan.acceptanceCriteria:value.acceptanceCriteria});setPlan(null);setError('');}catch(e){setError(e.message);}}
 return <details className="org-details org-execution-plan" open={(value.checklist||[]).length>0||!!plan}><summary>检查清单与 AI 建议{value.checklist?.length?' · '+value.checklist.length+' 项':''}</summary><ChecklistFields items={value.checklist||[]} onChange={checklist=>onChange({...value,checklist})} disabled={busy}/><div className="org-plan-generate"><button type="button" className="button secondary" disabled={busy||!home?.organization.settings.aiEnabled||!value.body?.trim()||value.body.length>8000||(value.checklist||[]).some(i=>!i.text.trim())} onClick={generate}><Sparkles size={16}/>{busy?'正在生成建议…':'AI 生成步骤与验收标准'}</button><p className="org-hint">{home?.organization.settings.aiEnabled?'把当前内容、已有步骤和标准发送给百炼，建议经你确认后加入草稿。':'组织开启 AI 后可生成建议，也可直接手动添加步骤。'}</p></div>
 {plan&&<div className="org-ai-result"><strong>建议草稿 · 选择需要的内容</strong>{plan.steps.map((s,i)=><label className="org-plan-option" key={i}><input type="checkbox" checked={selected.includes(i)} onChange={e=>setSelected(old=>e.target.checked?[...old,i]:old.filter(k=>k!==i))}/><span>{s.text}<small>{s.required?'建议必做':'可选'}</small></span></label>)}{plan.acceptanceCriteria&&<><p className="org-body">{plan.acceptanceCriteria}</p><label className="check-label"><input type="checkbox" checked={useCriteria} onChange={e=>setUseCriteria(e.target.checked)}/>{value.acceptanceCriteria?.trim()?'用建议替换已有验收标准':'使用建议的验收标准'}</label></>}{plan.questions?.length>0&&<div className="org-plan-questions"><strong>还需要你确认</strong><ul>{plan.questions.map(q=><li key={q}>{q}</li>)}</ul></div>}<div className="org-actions"><button type="button" className="button primary" disabled={!selected.length&&!useCriteria} onClick={apply}>加入当前草稿</button><button type="button" className="text-button" onClick={()=>setPlan(null)}>收起建议</button></div><p className="org-hint">相同步骤不会重复添加，加入后仍可修改顺序、文字和必做设置。</p></div>}{error&&<p role="alert" className="form-error">{error}</p>}</details>;
}
export function TaskExecution({data,home,busy,onAction,delivery,onDeliveryChange}){
 const t=data.task,p=t.permissions,live=['todo','doing'].includes(t.status)&&!t.archivedAt,canCheck=live&&p.submit&&(!t.acceptRequired||!!t.acceptedAt),canLink=live&&(p.manage||canCheck),items=data.checklist||[],links=data.deliverables||[],removed=links.filter(l=>l.removedAt),progress=t.checklistProgress||{};
 const name=id=>home.members.find(m=>m.id===id)?.name||'已离开成员';
 const link=l=><article key={l.id} className="org-delivery"><div><a href={l.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{l.label} ↗</a><small>{new URL(l.url).hostname} · {name(l.userId)} · {new Date(l.createdAt).toLocaleDateString('zh-CN')}</small></div>{canLink&&(p.manage||l.userId===home.me.id)&&<button type="button" className="text-button" disabled={busy} onClick={()=>onAction('deliverable-state',{id:l.id,removed:!l.removedAt})}>{l.removedAt?'恢复':'移除'}</button>}</article>;
 return <><section className="org-execution"><div className="section-heading"><h3>执行清单{items.length?' · '+progress.done+'/'+progress.total:''}</h3></div>{items.map(i=><label className={'org-step-check '+(i.completedAt?'done':'')} key={i.id}><input aria-label={i.text+(i.required?' 必做':' 可选')} type="checkbox" disabled={busy||!canCheck} checked={!!i.completedAt} onChange={e=>onAction('checklist-check',{itemId:i.id,done:e.target.checked})}/><span>{i.text}<small>{i.required?'必做':'可选'}{i.completedAt?' · '+name(i.completedBy)+' 已完成':''}</small></span></label>)}{!items.length&&<p className="org-hint">{p.edit?'编辑内容时可添加检查清单，或让 AI 生成步骤。':'此任务尚未设置检查清单。'}</p>}{items.length>0&&<p className="org-hint">{progress.requiredDone<progress.required?`还有 ${progress.required-progress.requiredDone} 项必做步骤。`:'必做步骤已完成。'}{t.acceptRequired&&!t.acceptedAt?'请先确认接收，再更新执行进度。':!p.submit?'执行进度由负责人或协作者确认。':''}</p>}</section>
 <section className="org-execution"><h3>交付链接 <small>{links.filter(l=>!l.removedAt).length}</small></h3>{links.filter(l=>!l.removedAt).map(link)}{canLink&&<details className="org-details"><summary>添加交付链接</summary><form className="org-form" onSubmit={async e=>{e.preventDefault();await onAction('deliverable-add',delivery);}}><label>资料名称<input disabled={busy} required maxLength={100} value={delivery.label} onChange={e=>onDeliveryChange({...delivery,label:e.target.value})} placeholder="例如：最终报价方案"/></label><label>资料链接<input disabled={busy} type="url" required maxLength={2048} value={delivery.url} onChange={e=>onDeliveryChange({...delivery,url:e.target.value})} placeholder="https://…"/></label><p className="org-hint">链接随任务权限展示，访问资料仍由原平台授权。请确认参与人能打开；系统不会自动抓取链接内容。</p><button className="button secondary" disabled={busy||!delivery.label.trim()||!delivery.url.trim()}>添加链接</button></form></details>}{removed.length>0&&<details><summary>已移除的链接 · {removed.length}</summary>{removed.map(link)}</details>}</section></>;
}
