import React from 'react';
import {ArrowRight,Check,CheckCheck,Clock,Flag,CalendarDays,Bell,FileText,LockKeyhole,Users,Link2,Send,ClipboardCheck,RotateCcw} from 'lucide-react';

function FlowNode({icon:Icon,title,children,tone=''}){return <div className={'guide-flow-node '+tone}><Icon size={21} strokeWidth={1.6}/><strong>{title}</strong><span>{children}</span></div>;}
export function GuideDiagram({kind,title,description}){
 return <figure className={'guide-diagram guide-diagram-'+kind}><figcaption><span className="guide-small-label">图解 / {kind==='time'?'01':kind==='quadrants'?'02':kind==='sharing'?'03':'04'}</span><h3>{title}</h3></figcaption>
  {kind==='time'&&<><div className="guide-time-track"><div className="guide-time-item"><div className="guide-time-icon"><Bell size={20}/></div><small>周三 · 13:50</small><strong>提醒我</strong><span>提前准备好资料</span></div><div className="guide-time-item featured"><div className="guide-time-icon"><CalendarDays size={20}/></div><small>周三 · 14:00</small><strong>开始做</strong><span>计划执行 · 预计 90 分钟</span></div><div className="guide-time-item"><div className="guide-time-icon"><Flag size={20}/></div><small>周五 · 18:00</small><strong>最晚交付</strong><span>截止时间</span></div></div><div className="guide-time-caption"><Clock size={15}/>计划回答「什么时候做」，截止回答「最晚何时完成」。</div></>}
  {kind==='quadrants'&&<div className="guide-matrix"><div className="guide-matrix-cell urgent-important"><span>01 / 重要 · 紧急</span><strong>优先处理</strong><p>例如：今天必须修复的关键故障</p><small>对目标有影响，也有时间压力</small></div><div className="guide-matrix-cell important"><span>02 / 重要 · 不紧急</span><strong>留出时间</strong><p>例如：能力学习、长期项目准备</p><small>主动安排，避免一直往后推</small></div><div className="guide-matrix-cell urgent"><span>03 / 不重要 · 紧急</span><strong>控制投入</strong><p>例如：临时但影响较小的事务</p><small>评估是否简化或请人协助</small></div><div className="guide-matrix-cell later"><span>04 / 不重要 · 不紧急</span><strong>稍后再看</strong><p>例如：可做可不做的零散想法</p><small>保留选择，不必马上行动</small></div></div>}
  {kind==='sharing'&&<div className="guide-sharing-flow"><FlowNode icon={LockKeyhole} title="私人记录" tone="private">仅自己的账号可见</FlowNode><div className="guide-sharing-branches"><div><span className="guide-branch-label"><ArrowRight size={16}/>选择内容与范围</span><FlowNode icon={FileText} title="只读快照">手动更新 · 可以撤回</FlowNode></div><div><span className="guide-branch-label"><ArrowRight size={16}/>确认后生成</span><FlowNode icon={Users} title="独立组织任务">在组织内执行与验收</FlowNode></div></div><div className="guide-sharing-note"><LockKeyhole size={16}/><span>私人原文、关联历史及后续修改<br/>不会自动公开。</span></div></div>}
  {kind==='execution'&&<><ol className="guide-execution-flow">{[[FileText,'发布任务','从草稿到待开始'],[CheckCheck,'确认接收','按任务要求接手'],[ClipboardCheck,'开始执行','完成必做步骤'],[Send,'提交验收','说明与交付链接'],[Check,'验收通过','任务已完成']].map(([Icon,label,help],i)=><li key={label}><span className="guide-execution-number">0{i+1}</span><Icon size={23} strokeWidth={1.5}/><strong>{label}</strong><small>{help}</small>{i<4&&<ArrowRight className="guide-connector" size={16}/>}</li>)}</ol><div className="guide-execution-branches"><span><RotateCcw size={15}/>退回修改 → 补充执行 → 再次提交</span><span><Link2 size={15}/>无需验收 → 完成必做项后直接完成任务</span></div></>}
  <p className="guide-figure-note">{description}</p>
 </figure>;
}
