import {GuideLink} from './GuideLink';
import React,{useState,useEffect,useRef,useCallback} from 'react';
import {ArrowLeft,Plus,Search,RefreshCw,Building2,Bell} from 'lucide-react';
import {TaskComposer,ShareComposer,MemberSelect,statuses} from './OrgForms';
import {OrgTaskDetail} from './OrgTaskDetail';
import {OrgLibrary} from './OrgLibrary';
import {OrgManage} from './OrgManage';
import {OrgBoard} from './OrgBoard';
import {dayKey} from './model';
import './organizations.css';
const tabs={dashboard:'工作台',tasks:'全部任务',projects:'项目',members:'成员',shares:'只读分享',notifications:'消息',library:'草稿与模板',settings:'组织设置'};
const noticeNames={assigned:'任务分配',assignment:'任务改派',publish:'任务发布',due:'截止临近',overdue:'任务逾期',mentioned:'讨论中提到你',block:'阻塞反馈',complete:'提交完成',approve:'验收通过',return:'退回修改',request:'变更申请','resolve-request':'申请处理',reopen:'重新打开',cancel:'任务取消',snoozed:'稍后提醒'};
const deliveryNames={org_disabled:'组织未开启微信',not_enabled:'尚未开启个人组织提醒',not_bound:'尚未连接微信',muted:'本任务已静音',snoozed:'已稍后提醒',quiet:'静默时段后发送',digest:'等待每日汇总',expired:'仅站内保留',acknowledged:'已知晓，不再外发',obsolete:'任务变化，仅站内保留',pending:'待发送',sending:'提交中',queued:'平台已受理',delivered:'平台报告投递成功',failed:'投递失败',unknown:'投递待确认',cancelled:'已取消外发'};
function readView(user,id){try{return JSON.parse(localStorage.getItem('me-org-view:'+user+':'+id))||{};}catch{return {};}}
export function OrganizationHub({workspace,user,Modal,initial,onPersonal}){
 const [libraryKey,setLibraryKey]=useState(0),[organizations,setOrganizations]=useState([]),[orgId,setOrgId]=useState(initial.orgId||readView(user.id,'last').orgId||''),[page,setPage]=useState(initial.mode==='mine'?'mine':'dashboard'),[home,setHome]=useState(null),[tasks,setTasks]=useState([]),[notices,setNotices]=useState([]),[shares,setShares]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[mode,setMode]=useState('list'),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[filter,setFilter]=useState({}),[selected,setSelected]=useState([]),[composer,setComposer]=useState(null),[detail,setDetail]=useState(initial.taskId?{id:initial.taskId}:null),[create,setCreate]=useState(false),[newName,setNewName]=useState(''),[joining,setJoining]=useState(''),[inviteCode,setInviteCode]=useState(()=>sessionStorage.getItem('me-org-invite')||''),[busy,setBusy]=useState(false),[batch,setBatch]=useState(null),[connected,setConnected]=useState(navigator.onLine);const seq=useRef(0),orgRef=useRef(orgId),operations=useRef(new Map()),seedUsed=useRef(false),newOrgId=useRef(crypto.randomUUID()),filterInit=useRef('');orgRef.current=orgId;
 const api=useCallback((path,opt)=>workspace.api('/api/organizations/'+orgId+path,{signal:AbortSignal.timeout(path.startsWith('/ai')||path.startsWith('/voice')?60000:15000),...opt}),[workspace.api,orgId]);
 async function loadOrganizations(){const r=await workspace.api('/api/organizations');setOrganizations(r.organizations);return r.organizations;}
 async function refresh(){const run=++seq.current;try{if(!navigator.onLine)throw new Error('组织需要联网使用，请恢复网络后重试');await loadOrganizations();if(page==='mine'){const r=await workspace.api('/api/organizations/mine');if(run===seq.current){setTasks(r.tasks);setConnected(true);setError('');}return;}if(!orgId)return;const [h,t,n,s]=await Promise.all([api(''),api('/tasks?archived='+(filter.archived?'true':'false')+(query?'&q='+encodeURIComponent(query):'')),api('/notifications'),api('/shares')]);if(run!==seq.current)return;setHome(h);setTasks(t.tasks);setNotices(n.notifications);setShares(s.shares);setConnected(true);setError('');}catch(e){if(run!==seq.current)return;if([401,403,404].includes(e.status)){setHome(null);setTasks([]);setShares([]);setNotices([]);setDetail(null);setComposer(null);}setConnected(false);setError(e.status?e.message:'连接暂时中断，正在输入的内容仍保留在当前页面。');}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,20000),offline=()=>{seq.current++;setConnected(false);setError('连接已中断，页面数据可能不是最新；输入留在当前页面，联网后继续保存。');};window.addEventListener('offline',offline);window.addEventListener('online',refresh);return()=>{seq.current++;clearInterval(timer);window.removeEventListener('offline',offline);window.removeEventListener('online',refresh);};},[orgId,page,filter.archived,query]);
 useEffect(()=>{if(!home||filterInit.current===orgId)return;filterInit.current=orgId;const saved=readView(user.id,orgId);setMode(saved.mode||'list');setFilter(saved.filter||(!home.admin&&!home.scopes.some(s=>s.leadId===user.id)?{mine:true}:{}));},[home,orgId]);
 useEffect(()=>{if(!orgId||filterInit.current!==orgId)return;try{localStorage.setItem('me-org-view:'+user.id+':'+orgId,JSON.stringify({mode,filter}));localStorage.setItem('me-org-view:'+user.id+':last',JSON.stringify({orgId}));}catch{}},[mode,filter,orgId]);
 useEffect(()=>{if(home&&initial.seed&&!seedUsed.current){seedUsed.current=true;setComposer({type:initial.type||'task',seed:initial.seed});}},[home]);
 async function action(kind,data,version){if(!navigator.onLine)throw new Error('请联网后操作');const key=JSON.stringify([orgId,kind,version,data]),operationId=operations.current.get(key)||crypto.randomUUID();operations.current.set(key,operationId);const r=await api('/actions/'+kind,{method:'POST',body:JSON.stringify({operationId,...(version?{version}:{}),data})});setMessage('已保存');return r;}
 async function safe(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function changeOrg(id){seq.current++;setHome(null);setTasks([]);setShares([]);setNotices([]);setOrgId(id);setPage('dashboard');setDetail(null);setComposer(null);setFilter({});setSelected([]);setMessage('');const url=new URL(location.href);url.searchParams.delete('orgTask');url.searchParams.delete('orgNotice');if(id)url.searchParams.set('org',id);else url.searchParams.delete('org');history.replaceState(null,'',url);}
 async function join(code){await safe(async()=>{const r=await workspace.api('/api/organizations/join',{method:'POST',body:JSON.stringify({code:code.trim()})});sessionStorage.removeItem('me-org-invite');setInviteCode('');setJoining('');history.replaceState(null,'',location.pathname);changeOrg(r.id);await loadOrganizations();});}
 const isManager=home?.admin||home?.scopes.some(s=>s.leadId===user.id);
 const active=home?.members.filter(m=>m.state==='active').map(m=>m.id)||[],today=dayKey();
 const matches=t=>{const c=t.content;if(filter.action&&!((t.permissions.accept&&t.acceptRequired&&!t.acceptedAt&&['todo','doing'].includes(t.status))||(t.permissions.review&&t.status==='review')||(t.assigneeId===user.id&&t.status==='doing')))return false;if(filter.mine&&t.assigneeId!==user.id||filter.created&&t.creatorId!==user.id||filter.project&&t.projectId!==filter.project||filter.department&&t.departmentId!==filter.department||filter.assignee&&t.assigneeId!==filter.assignee||filter.source&&t.source!==filter.source||filter.status&&t.status!==filter.status)return false;if(filter.metric){const live=!['done','cancelled','draft'].includes(t.status);if(filter.metric==='unassigned'&&(!live||t.assigneeId&&active.includes(t.assigneeId)))return false;if(filter.metric==='due'&&(!live||c.dueDate!==today))return false;if(filter.metric==='overdue'&&(!live||!c.dueDate||c.dueDate>=today))return false;if(filter.metric==='blocked'&&(!live||!t.blockedReason))return false;if(filter.metric==='review'&&t.status!=='review')return false;}return true;};const visible=tasks.filter(matches),formal=tasks.filter(t=>t.status!=='draft'&&!t.archivedAt&&(isManager||t.assigneeId===user.id||t.creatorId===user.id||t.collaboratorIds.includes(user.id))),metricCounts={unassigned:formal.filter(t=>!['done','cancelled'].includes(t.status)&&(!t.assigneeId||!active.includes(t.assigneeId))).length,due:formal.filter(t=>!['done','cancelled'].includes(t.status)&&t.content.dueDate===today).length,overdue:formal.filter(t=>!['done','cancelled'].includes(t.status)&&t.content.dueDate&&t.content.dueDate<today).length,blocked:formal.filter(t=>!['done','cancelled'].includes(t.status)&&t.blockedReason).length,review:formal.filter(t=>t.status==='review').length};
 function openTask(t,initialAction){if(t.orgId!==orgId){changeOrg(t.orgId);setDetail({id:t.id,initialAction});}else setDetail({id:t.id,initialAction});}
 async function move(t,value,type,mine){if(type==='quadrant'){await safe(async()=>{if(mine){await action('task-preference',{id:t.id,payload:{muted:!!t.preference.muted,snoozeMinutes:0,quadrant:value==='unassigned'?null:value,focusDate:t.preference.focusDate||null}},t.version);}else{const d=await api('/tasks/'+t.id);await action('content',{id:t.id,payload:{...d.task.content,quadrant:value==='unassigned'?null:value}},t.version);}await refresh();});return;}if(value===t.status)return;if(value==='doing'&&t.status==='todo')await safe(async()=>{await action('start',{id:t.id,payload:{}},t.version);await refresh();});else if(['done','review'].includes(value)&&['todo','doing'].includes(t.status))openTask(t,'complete');else if(value==='done'&&t.status==='review')openTask(t,'approve');else if(value==='doing'&&t.status==='review')openTask(t,'return');else if(value==='todo'&&['done','cancelled','review'].includes(t.status))openTask(t,'reopen');else setMessage('请在任务详情中处理当前状态，再调整看板位置。');}
 const allNotice=notices.filter(n=>!n.acknowledgedAt).length;
 return <div className="org-shell"><aside className="org-sidebar"><button className="brand" onClick={onPersonal}>me<span>.</span></button><label className="org-space-label">工作空间<select aria-label="切换空间" value={page==='mine'?'mine':orgId} onChange={e=>{if(e.target.value==='personal')onPersonal();else if(e.target.value==='mine'){setPage('mine');setHome(null);setTasks([]);}else changeOrg(e.target.value);}}><option value="personal">个人空间</option><option value="mine">我的组织任务</option><option value="">创建 / 加入组织</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}{o.state==='paused'?'（暂停）':''}</option>)}</select></label>{orgId&&page!=='mine'&&<nav aria-label="组织导航">{Object.entries(tabs).map(([key,label])=><button key={key} className={'nav-item '+(page===key?'active':'')} onClick={()=>{setPage(key);setSelected([]);}}>{label}{key==='notifications'&&allNotice>0&&<small>{allNotice}</small>}</button>)}</nav>}<button className="settings-link org-back" onClick={onPersonal}><ArrowLeft size={16}/>返回个人空间</button></aside><main className="org-main"><header className="org-top"><div><small>组织协作</small><h1>{page==='mine'?'我的组织任务':home?.organization.name||'工作空间'}</h1></div><div className="org-actions"><GuideLink section="organizations"/><button className="icon-button" aria-label="刷新组织数据" onClick={refresh}><RefreshCw size={18}/></button><button className="button secondary" onClick={()=>{newOrgId.current=crypto.randomUUID();setCreate(true);}}>创建组织</button>{home?.organization.state==='active'&&<button className="button primary" onClick={()=>setComposer({type:'task'})}><Plus size={17}/>新建</button>}</div></header>
 {error&&<div className="org-banner form-error" role="alert">{error}<button className="text-button" onClick={refresh}>重新加载</button></div>}{message&&<div className="org-banner" role="status">{message}<button className="text-button" onClick={()=>setMessage('')}>关闭</button></div>}
 {inviteCode&&<section className="org-panel"><h2>你收到了一份组织邀请</h2><p>接收后才加入组织。当前登录邮箱：{user.email}</p><button className="button primary" disabled={busy} onClick={()=>join(inviteCode)}>确认加入</button><button className="button secondary" onClick={()=>{sessionStorage.removeItem('me-org-invite');setInviteCode('');history.replaceState(null,'',location.pathname);}}>暂不加入</button></section>}
 {!orgId&&page!=='mine'&&<><div className="org-welcome"><Building2 size={34}/><h2>为共同的工作建一个空间</h2><p>派发、执行、反馈与验收放在一起。私人记录仍留在个人空间。</p></div><div className="org-scope-grid">{organizations.map(o=><button key={o.id} className="org-panel org-org-choice" onClick={()=>changeOrg(o.id)}><strong>{o.name}</strong><small>{{owner:'所有者',admin:'管理员',member:'成员'}[o.role]}</small><span>进入组织 →</span></button>)}</div><form className="org-panel org-form" onSubmit={e=>{e.preventDefault();let code=joining.trim();try{code=new URL(code).hash.replace('#org-invite=','');}catch{}join(code);}}><label>粘贴组织邀请链接<input value={joining} onChange={e=>setJoining(e.target.value)} placeholder="由组织管理员提供"/></label><button className="button secondary" disabled={busy||!joining.trim()}>加入组织</button></form></>}
 {page==='mine'&&<><p className="org-hint">汇总分给我、我创建、我协作和待我验收的组织任务。</p><OrgBoard tasks={visible} home={home} mode="list" onOpen={openTask} onMove={move} selected={[]} mine/></>}
 {home&&page!=='mine'&&<>{home.organization.state==='paused'&&<div className="org-banner">组织已暂停。管理员可导出数据，或在设置中恢复使用。</div>}{['dashboard','tasks'].includes(page)&&<>
 {page==='dashboard'&&<div className="org-metrics">{Object.entries(isManager?{unassigned:'待分派 / 交接',due:'今日到期',overdue:'已逾期',blocked:'被阻塞',review:'待验收'}:{due:'今日到期',overdue:'已逾期',blocked:'被阻塞'}).map(([k,label])=><button key={k} className={filter.metric===k?'active':''} onClick={()=>setFilter({...filter,metric:filter.metric===k?'':k})}><span>{label}</span><strong>{metricCounts[k]}</strong></button>)}</div>}
 <div className="org-toolbar"><div className="filter-tabs">{Object.entries({list:'列表',kanban:'任务看板',quadrant:'四象限',gantt:'甘特图'}).map(([k,label])=><button key={k} className={mode===k?'active':''} onClick={()=>setMode(k)}>{label}</button>)}</div><button className="icon-button" aria-label="搜索组织任务" onClick={()=>setSearch(!search)}><Search size={18}/></button></div>{search&&<input className="org-search" aria-label="搜索任务" placeholder="输入关键词" value={query} onChange={e=>setQuery(e.target.value)}/>}
 <div className="org-filters"><button className={'button secondary '+(filter.mine?'selected':'')} onClick={()=>setFilter({...filter,mine:!filter.mine,created:false})}>分给我</button><button className={'button secondary '+(filter.created?'selected':'')} onClick={()=>setFilter({...filter,created:!filter.created,mine:false})}>我创建</button><button className={'button secondary '+(filter.action?'selected':'')} onClick={()=>setFilter({...filter,action:!filter.action,mine:false,created:false})}>待我处理</button><select aria-label="任务状态筛选" value={filter.status||''} onChange={e=>setFilter({...filter,status:e.target.value})}><option value="">全部状态</option>{Object.entries(statuses).map(([k,s])=><option key={k} value={k}>{s}</option>)}</select>{['project','department'].map(k=><select key={k} aria-label={k==='project'?'项目筛选':'部门筛选'} value={filter[k]||''} onChange={e=>setFilter({...filter,[k]:e.target.value})}><option value="">{k==='project'?'全部项目':'全部部门'}</option>{home.scopes.filter(s=>s.kind===k).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>)}<select aria-label="负责人筛选" value={filter.assignee||''} onChange={e=>setFilter({...filter,assignee:e.target.value})}><option value="">全部负责人</option>{home.members.map(m=><option key={m.id} value={m.id}>{m.name}{m.state!=='active'?'（已离开）':''}</option>)}</select><select aria-label="任务来源筛选" value={filter.source||''} onChange={e=>setFilter({...filter,source:e.target.value})}><option value="">全部来源</option><option value="self">自主登记</option><option value="assigned">管理者派发</option><option value="personal">私人内容生成</option><option value="repeat">重复计划</option></select><label className="check-label"><input type="checkbox" checked={!!filter.archived} onChange={e=>setFilter({...filter,archived:e.target.checked})}/>归档</label>{Object.values(filter).some(Boolean)&&<button className="text-button" onClick={()=>{setFilter({});setSelected([]);}}>清除筛选</button>}</div>
 {selected.length>0&&<div className="org-banner">已选择 {selected.length} 项<button className="button secondary" onClick={()=>setBatch({items:tasks.filter(t=>selected.includes(t.id)).map(t=>({id:t.id,version:t.version})),action:'assign',assigneeId:null,reason:''})}>批量改派 / 交接</button><button className="text-button" onClick={()=>setSelected([])}>取消选择</button></div>}
 <OrgBoard tasks={visible} home={home} mode={mode} mine={!!filter.mine} onOpen={openTask} onMove={move} selected={selected} onSelect={setSelected}/>
 {page==='dashboard'&&isManager&&<details className="org-panel"><summary>可见任务的工作量概览</summary><p className="org-hint">统计当前筛选下未完成的正式任务。预计投入不包含未填写时长的事项。</p><div className="org-members">{home.members.filter(m=>m.state==='active').map(m=>{const own=visible.filter(t=>t.assigneeId===m.id&&!['done','cancelled','draft'].includes(t.status));return <article key={m.id}><strong>{m.name}</strong><span>{own.length} 项 · 已填 {own.reduce((n,t)=>n+(t.content.durationMinutes||0),0)} 分钟 · {own.filter(t=>!t.content.durationMinutes).length} 项时长待补</span></article>;})}</div></details>}</>}
 {page==='library'&&<OrgLibrary key={orgId+':'+libraryKey} api={api} action={action} onCompose={v=>setComposer({type:'task',...v})} onTask={(id,restored)=>setDetail({id,restored})}/>}
 {['members','projects','settings'].includes(page)&&<OrgManage key={orgId+page} page={page} home={home} api={api} action={action} refresh={refresh} Modal={Modal}/>}
 {page==='shares'&&<section><p className="org-hint">以下为对你开放的只读快照，不进入组织任务统计。</p>{shares.map(s=><article key={s.id} className="org-panel"><h3>{s.snapshot.title||s.snapshot.body.slice(0,60)}</h3><p className="org-body">{s.snapshot.body}</p><small>{home.members.find(m=>m.id===s.ownerId)?.name} · 分享版本 {s.version}</small>{s.ownerId===user.id&&<div className="org-actions"><button className="button secondary" onClick={()=>safe(async()=>{await action('revoke-share',{id:s.id},s.version);await refresh();})}>撤销分享</button><button className="button secondary" onClick={()=>{const source=workspace.state.entries.find(e=>e.id===s.sourceId);if(source&&!source.pending)setComposer({type:'share',seed:source,existing:s});else setError('请先在个人空间同步原记录');}}>更新分享快照</button><button className="button secondary" onClick={()=>{const source=workspace.state.entries.find(e=>e.id===s.sourceId);if(source&&!source.pending)setComposer({type:'task',seed:{...source,...s.snapshot}});else setError('请先在个人空间同步原记录');}}>生成组织任务</button></div>}</article>)}{!shares.length&&<div className="board-empty">还没有对你开放的分享。可在个人记录详情中选择“只读分享”。</div>}</section>}
 {page==='notifications'&&<section><p className="org-hint">平台投递、已知晓和任务完成分别记录。这里的按钮只确认知晓，不会改变任务状态。</p>{notices.map(n=><article className="org-panel org-notice" key={n.id}><div><strong>{noticeNames[n.kind]||'任务动态'}</strong><p>{new Date(n.createdAt).toLocaleString('zh-CN')} · {deliveryNames[n.deliveryState]}</p><span>{n.acknowledgedAt?'已知晓':'待查看'}</span></div><div className="org-actions"><button className="button secondary" onClick={()=>setDetail({id:n.taskId})}>查看任务</button>{!n.acknowledgedAt&&<button className="button primary" disabled={busy} onClick={()=>safe(async()=>{await action('ack',{id:n.id});await refresh();})}>我已知晓</button>}</div></article>)}{!notices.length&&<div className="board-empty"><Bell size={24}/> 暂无消息</div>}</section>}
 </>}
 <footer className="page-footer"><span>me.</span><a href="https://beian.miit.gov.cn/" target="_blank" rel="noreferrer">京ICP备2026054579号</a></footer></main>
 {create&&<Modal title="创建组织" onClose={()=>setCreate(false)}><form className="org-form" onSubmit={e=>{e.preventDefault();safe(async()=>{const r=await workspace.api('/api/organizations',{method:'POST',body:JSON.stringify({id:newOrgId.current,name:newName})});setCreate(false);setNewName('');changeOrg(r.id);});}}><label>组织名称<input required maxLength={60} value={newName} onChange={e=>setNewName(e.target.value)} autoFocus/></label><p className="org-hint">你将成为组织所有者。创建后可邀请同事，所有既有私人记录保持私密。</p>{error&&<p className="form-error">{error}</p>}<button className="button primary" disabled={busy||!newName.trim()}>创建</button></form></Modal>}
 {home&&composer?.type==='task'&&<TaskComposer home={home} workspace={workspace} api={api} action={action} Modal={Modal} seed={composer.seed} restored={composer.restored} onClose={()=>{setComposer(null);setLibraryKey(n=>n+1);}} onCreated={id=>{setComposer(null);setLibraryKey(n=>n+1);refresh();if(id)setDetail({id});}}/>}{home&&composer?.type==='share'&&<ShareComposer home={home} seed={composer.seed} existing={composer.existing} action={action} Modal={Modal} onClose={()=>{setComposer(null);setLibraryKey(n=>n+1);}} onSaved={()=>{setComposer(null);setPage('shares');refresh();}}/>}
 {home&&detail&&<OrgTaskDetail key={orgId+detail.id} id={detail.id} initialAction={detail.initialAction} restored={detail.restored} home={home} api={api} action={action} Modal={Modal} onClose={()=>{setDetail(null);setLibraryKey(n=>n+1);}} onChanged={refresh}/>}
 {home&&batch&&<Modal title="批量操作 · 请核对影响范围" onClose={()=>setBatch(null)}><form className="org-form" onSubmit={e=>{e.preventDefault();safe(async()=>{await action('batch',batch);setBatch(null);setSelected([]);await refresh();});}}><p>将影响下列 {selected.length} 项任务；全部权限和版本通过后才会保存。</p><ul>{tasks.filter(t=>selected.includes(t.id)).map(t=><li key={t.id}>{t.content.title}</li>)}</ul><label>操作<select value={batch.action} onChange={e=>setBatch({...batch,action:e.target.value})}><option value="assign">改派 / 交接</option><option value="archive">归档 / 恢复归档</option><option value="cancel">取消</option></select></label>{batch.action==='assign'&&<MemberSelect home={home} label="新的负责人" value={batch.assigneeId} onChange={assigneeId=>setBatch({...batch,assigneeId})}/>}<label>说明<textarea value={batch.reason} onChange={e=>setBatch({...batch,reason:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary" disabled={busy}>确认处理 {selected.length} 项</button></form></Modal>}
 </div>;
}
export function MyOrganizationTasks({workspace,onOpen}){const [tasks,setTasks]=useState([]);useEffect(()=>{let alive=true;const refresh=async()=>{try{const r=await workspace.api('/api/organizations/mine');if(alive&&navigator.onLine)setTasks(r.tasks.filter(t=>!['done','cancelled'].includes(t.status)));}catch{if(alive)setTasks([]);}};refresh();const timer=setInterval(refresh,30000),offline=()=>setTasks([]);window.addEventListener('offline',offline);return()=>{alive=false;clearInterval(timer);window.removeEventListener('offline',offline);};},[workspace.api]);if(!tasks.length)return null;return <section className="org-personal-tasks"><div className="section-heading"><h2>我的组织任务 <span>{tasks.length}</span></h2><button className="text-button" onClick={()=>onOpen({mode:'mine'})}>查看全部</button></div>{tasks.slice(0,6).map(t=><button className="org-personal-row" key={t.id} onClick={()=>onOpen({orgId:t.orgId,taskId:t.id})}><strong>{t.content.title}</strong><span>{t.organizationName} · {statuses[t.status]}{t.content.dueDate?' · '+t.content.dueDate+' 截止':''}</span></button>)}</section>;}
