import React,{useState,useEffect,useRef} from 'react';
import {GripVertical} from 'lucide-react';
import {createBoardDrag} from './board-drag';
import {statuses,quadrants} from './OrgForms';
import {dayKey} from './model';
export function OrgBoard({tasks,home,mode,onOpen,onMove,selected,onSelect,mine=false}){
 const [dragId,setDragId]=useState(null),[target,setTarget]=useState(''),[move,setMove]=useState(null),[days,setDays]=useState(7),[start,setStart]=useState(dayKey());const ref=useRef(null),drop=useRef(null),native=useRef(null);
 const columns=mode==='quadrant'?{unassigned:'待确认',...quadrants}:{todo:'待开始',doing:'进行中',review:'待验收',done:'已完成'};
 function end(){setDragId(null);setTarget('');native.current=null;}
 function apply(target,id){const value=target.split(':')[1];if(!(value in columns))return;const task=tasks.find(t=>t.id===id);if(task)onMove(task,value,mode,mine);end();}drop.current=apply;
 if(!ref.current)ref.current=createBoardDrag({onStart:setDragId,onTarget:setTarget,onDrop:(v,id)=>drop.current(v,id),onEnd:end});useEffect(()=>()=>ref.current.cancel(),[]);
 const name=id=>home?.members.find(m=>m.id===id)?.name||'待分派';
 const card=t=><article key={t.id} className={`org-task-card ${dragId===t.id?'is-dragging':''}`} draggable onDragStart={e=>{native.current=t.id;e.dataTransfer.setData('text/plain',t.id);setDragId(t.id);}} onDragEnd={end}><div className="org-card-row">{onSelect&&t.permissions.manage&&<input type="checkbox" aria-label={'选择 '+t.content.title} checked={selected.includes(t.id)} onChange={e=>onSelect(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/>}<button className="org-card-title" onClick={()=>onOpen(t)}>{t.content.title||'无标题'}</button>{mode!=='list'&&<button className="board-card-grip" aria-label={'移动 '+t.content.title} title="手机长按拖动，或点击选择位置" onPointerDown={e=>ref.current.down(e,t.id)} onPointerMove={ref.current.move} onPointerUp={ref.current.up} onPointerCancel={ref.current.cancel} onLostPointerCapture={ref.current.cancel} onContextMenu={e=>e.preventDefault()} onClick={()=>{if(!ref.current.consumeClick())setMove(t.id);}}><GripVertical size={16}/></button>}</div><div className="org-card-meta"><span>{t.organizationName||name(t.assigneeId)}</span><span>{statuses[t.status]}</span>{t.content.dueDate&&<span className={t.content.dueDate<dayKey()&&!['done','cancelled'].includes(t.status)?'warning':''}>{t.content.dueDate.slice(5)}{t.content.dueTime?' '+t.content.dueTime:''} 截止</span>}{t.checklistProgress?.total>0&&<span>清单 {t.checklistProgress.done}/{t.checklistProgress.total}</span>}{t.blockedReason&&<span className="warning">阻塞</span>}{t.reviewRequired&&<span>需验收</span>}{t.acceptRequired&&!t.acceptedAt&&<span>待接收</span>}</div>{move===t.id&&<select aria-label="移动到" defaultValue="" onChange={e=>{onMove(t,e.target.value,mode,mine);setMove(null);}}><option value="">选择位置</option>{Object.entries(columns).map(([k,s])=><option key={k} value={k}>{s}</option>)}</select>}</article>;
 if(mode==='list')return <div className="org-task-list">{tasks.map(card)}{!tasks.length&&<div className="board-empty">这里还没有任务。创建第一项，或调整筛选条件。</div>}</div>;
 if(mode==='gantt'){
  const left=Date.parse(start+'T00:00:00+08:00'),span=days*86400000,dated=[],pending=[];
  for(const t of tasks){const c=t.content,a=c.kind==='event'&&c.startAt?Date.parse(c.startAt):c.scheduledDate?Date.parse(c.scheduledDate+'T'+(c.scheduledTime||'00:00')+':00+08:00'):null,b=c.kind==='event'&&c.endAt?Date.parse(c.endAt):c.dueDate?Date.parse(c.dueDate+'T'+(c.dueTime||'23:59')+':00+08:00'):a&&c.durationMinutes&&c.scheduledTime?a+c.durationMinutes*60000:null;if(!a||!b){pending.push(t);if(b&&b>=left&&b<left+span)dated.push({t,a:b,b,milestone:true});continue;}if(b>=left&&a<left+span)dated.push({t,a,b});}
  return <><div className="org-inline"><label>起始日期<input type="date" value={start} onChange={e=>{if(e.target.value)setStart(e.target.value);}}/></label><label>时间范围<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>一周</option><option value={30}>一个月</option></select></label></div><p className="org-hint">横条表示计划开始至截止的窗口，不等于实际工时。菱形为仅有截止的节点。</p><div className="org-gantt" tabIndex={0} aria-label="组织甘特图，可横向滚动"><div style={{minWidth:days===7?760:1200}}><div className="org-gantt-row org-gantt-head"><strong>任务</strong><div className="org-gantt-dates">{Array.from({length:days},(_,i)=><span key={i}>{new Date(left+i*86400000).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric'})}</span>)}</div></div>{dated.map(({t,a,b,milestone})=><div className="org-gantt-row" key={t.id}><button onClick={()=>onOpen(t)}>{t.content.title}</button><div className="org-gantt-track"><button className={'org-gantt-bar '+(milestone?'milestone':'')} aria-label={t.content.title+' · '+(milestone?'截止节点':'计划窗口')} style={{left:Math.max(0,(a-left)/span*100)+'%',width:milestone?12:Math.max(1,(Math.min(left+span,b)-Math.max(a,left))/span*100)+'%'}} onClick={()=>onOpen(t)}>{milestone?'◆':t.content.title}</button></div></div>)}</div></div>{!dated.length&&<div className="board-empty">所选时间段暂无完整排程</div>}<details open={pending.length>0}><summary>待补排程 · {pending.length}</summary><p className="org-hint">缺少开始或结束信息的事项保留在这里，不推算时长。</p>{pending.map(card)}</details></>;
 }
 return <><div className={'org-columns '+(mode==='quadrant'?'quadrants':'')} >{Object.entries(columns).map(([key,label])=>{const list=tasks.filter(t=>mode==='quadrant'?(mine?t.preference.quadrant||t.content.quadrant||'unassigned':t.content.quadrant||'unassigned')===key&&!['done','cancelled','draft'].includes(t.status):t.status===key);return <section key={key} data-drop-target={mode+':'+key} className={'org-column '+(target===mode+':'+key?'drop-active':'')} onDragOver={e=>{if(native.current){e.preventDefault();setTarget(mode+':'+key);}}} onDrop={e=>{e.preventDefault();apply(mode+':'+key,native.current);}}><h3>{label}<span>{list.length}</span></h3>{list.map(card)}{!list.length&&<div className="org-column-empty">暂无任务</div>}</section>;})}</div>{tasks.filter(t=>t.status==='draft'||t.status==='cancelled').length>0&&<details><summary>草稿与已取消</summary>{tasks.filter(t=>t.status==='draft'||t.status==='cancelled').map(card)}</details>}</>;
}
