import React,{useState,useRef} from 'react';
import {useOrgDraft} from './useOrgDraft';
import {prepareAiItems,fieldNames,assignmentChoices} from './org-productivity';
import {ExecutionPlanEditor,ChecklistFields} from './ExecutionPlan';
import {taskQuality} from './execution-model';
import {VoiceInput} from './VoiceInput';
export const statuses={draft:'草稿',todo:'待开始',doing:'进行中',review:'待验收',done:'已完成',cancelled:'已取消'};
export const quadrants={'urgent-important':'重要 · 紧急',important:'重要 · 不紧急',urgent:'不重要 · 紧急',later:'不重要 · 不紧急'};
export const visibilityLabels={participants:'参与人和管理者',project:'项目成员和管理者',department:'部门成员和管理者',organization:'全组织'};
export const emptyContent=()=>({kind:'task',title:'',body:'',tags:[],scheduledDate:null,scheduledTime:null,dueDate:null,dueTime:null,durationMinutes:null,startAt:null,endAt:null,allDay:false,quadrant:null,acceptanceCriteria:'',checklist:[]});
export const selectedContent=e=>Object.fromEntries(Object.keys(emptyContent()).map(k=>[k,e?.[k]??emptyContent()[k]]));
export const emptyAssignment=id=>({assigneeId:id,reviewerId:null,projectId:null,departmentId:null,collaboratorIds:[],visibility:'participants',acceptRequired:false,reviewRequired:false});
export const assignmentOf=t=>Object.fromEntries(Object.keys(emptyAssignment(null)).map(k=>[k,t[k]]));
export function MemberSelect({home,value,onChange,label,allowEmpty=true,multiple=false,onlyManagers=false}){
 const [query,setQuery]=useState('');const active=home.members.filter(m=>m.state==='active'&&(!onlyManagers||['owner','admin'].includes(m.role)||home.scopes.some(s=>s.leadId===m.id))),chosen=multiple?(value||[]):value?[value]:[],filtered=active.filter(m=>(m.name+' '+m.id.slice(0,4)).toLowerCase().includes(query.toLowerCase()));
 const labelOf=m=>m.name+(m.id===home.me.id?'（我）':'')+' · '+m.id.slice(0,4);
 return <div className="org-member-picker"><span>{label}</span><details><summary>{chosen.length?active.filter(m=>chosen.includes(m.id)).map(labelOf).join('、')||'请重新选择':allowEmpty?'不设置':'请选择'}{multiple&&chosen.length>0?' · '+chosen.length+' 人':''}</summary><input type="search" aria-label={'搜索'+label} placeholder="搜索成员" value={query} onChange={e=>setQuery(e.target.value)}/><div className="org-member-options" role="group" aria-label={label}>{allowEmpty&&!multiple&&<label className="check-label"><input type="radio" checked={!value} onChange={()=>onChange(null)}/>不设置</label>}{filtered.map(m=><label className="check-label" key={m.id}><input type={multiple?'checkbox':'radio'} checked={chosen.includes(m.id)} onChange={()=>onChange(multiple?chosen.includes(m.id)?chosen.filter(id=>id!==m.id):[...chosen,m.id]:m.id)}/>{labelOf(m)}</label>)}{!filtered.length&&<p className="org-hint">没有匹配的可选成员</p>}</div></details></div>;
}
export function ContentFields({value:v,onChange,compact=false,hideKind=false,showChecklist=false}){const set=(k,value)=>onChange({...v,[k]:value});return <>{!hideKind&&<label>类别<select value={v.kind} onChange={e=>onChange({...v,kind:e.target.value,startAt:null,endAt:null,allDay:false})}><option value="note">想法</option><option value="task">待办</option><option value="event">日程</option></select></label>}<label>标题<input maxLength={200} value={v.title} onChange={e=>set('title',e.target.value)} placeholder="选填"/></label><label>正文<textarea required rows={compact?4:6} maxLength={10000} value={v.body} onChange={e=>set('body',e.target.value)}/></label><details className="org-details"><summary>时间、优先级与验收标准</summary><div className="org-fields"><label>计划日期<input type="date" value={v.scheduledDate||''} onChange={e=>set('scheduledDate',e.target.value||null)}/></label><label>计划时刻<input type="time" value={v.scheduledTime||''} onChange={e=>set('scheduledTime',e.target.value||null)}/></label><label>截止日期<input type="date" value={v.dueDate||''} onChange={e=>set('dueDate',e.target.value||null)}/></label><label>截止时刻<input type="time" value={v.dueTime||''} onChange={e=>set('dueTime',e.target.value||null)}/></label><label>预计投入（分钟）<input type="number" min={1} max={10080} value={v.durationMinutes||''} onChange={e=>set('durationMinutes',e.target.value?Number(e.target.value):null)}/></label><label>组织优先级<select value={v.quadrant||''} onChange={e=>set('quadrant',e.target.value||null)}><option value="">待确认</option>{Object.entries(quadrants).map(([k,s])=><option key={k} value={k}>{s}</option>)}</select></label>{v.kind==='event'&&['startAt','endAt'].map((k,i)=><label key={k}>{i?'日程结束':'日程开始'}<input type="datetime-local" value={v[k]?new Date(Date.parse(v[k])+8*3600000).toISOString().slice(0,16):''} onChange={e=>set(k,e.target.value?new Date(e.target.value+':00+08:00').toISOString():null)}/></label>)}</div><label>标签<input value={v.tags.join('，')} onChange={e=>set('tags',e.target.value.split(/[,，]/).map(s=>s.trim()).filter(Boolean).slice(0,12))}/></label><label>验收标准<textarea rows={2} maxLength={3000} value={v.acceptanceCriteria} onChange={e=>set('acceptanceCriteria',e.target.value)}/></label></details>{showChecklist&&<details className="org-details"><summary>检查清单 · {v.checklist?.length||0} 项</summary><ChecklistFields items={v.checklist||[]} onChange={checklist=>set('checklist',checklist)}/></details>}</>;}
export function AssignmentFields({home,value:v,onChange}){const choices=assignmentChoices(home,v),set=(k,x)=>onChange({...v,[k]:x});return <div className="org-assignment"><div className="org-fields">{['project','department'].map(kind=><label key={kind}>{kind==='project'?'所属项目':'管理部门'}<select value={v[kind+'Id']||''} onChange={e=>set(kind+'Id',e.target.value||null)}><option value="">不设置</option>{choices.scopes.filter(s=>s.kind===kind).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>)}<MemberSelect home={{...home,members:choices.members}} label="主要负责人" allowEmpty={choices.manager} value={v.assigneeId} onChange={x=>set('assigneeId',x)}/><label>谁可以查看<select value={v.visibility} onChange={e=>set('visibility',e.target.value)}>{Object.entries(visibilityLabels).filter(([k])=>choices.manager||k==='participants').map(([k,s])=><option key={k} value={k}>{s}</option>)}</select></label></div><p className="org-hint">{choices.manager?'正式任务由组织及所属范围的管理者管理。':'登记本人任务；先选择你负责的项目或部门，才可给该范围成员派发。'}草稿仅你可见。</p><details><summary>协作与验收</summary>{choices.manager&&<MemberSelect multiple home={{...home,members:choices.members}} label="协作者" value={v.collaboratorIds} onChange={x=>set('collaboratorIds',x)}/>}<label className="check-label"><input type="checkbox" checked={v.acceptRequired} onChange={e=>set('acceptRequired',e.target.checked)}/>需要负责人确认接收</label><label className="check-label"><input type="checkbox" checked={v.reviewRequired} onChange={e=>set('reviewRequired',e.target.checked)}/>提交完成后需要验收</label><MemberSelect home={{...home,members:choices.reviewers}} label="验收人" value={v.reviewerId} onChange={x=>set('reviewerId',x)}/></details></div>;}
export function TaskComposer({home,workspace,api,action,Modal,onClose,onCreated,seed,restored}){
 const saved=restored?.payload;
 const [content,setContent]=useState(()=>saved?.content||selectedContent(seed||{})),[kind,setKind]=useState(saved?.kind||seed?.kind||'auto'),[assignment,setAssignment]=useState(()=>saved?.assignment||seed?.assignment||emptyAssignment(home.me.id)),[items,setItems]=useState(saved?.items||null),[suggestions,setSuggestions]=useState(saved?.suggestions||null),[manual,setManual]=useState(saved?.manual||Object.keys(emptyContent()).filter(k=>k!=='body'&&seed?.[k])),[advice,setAdvice]=useState(saved?.advice||[]),[busy,setBusy]=useState(false),[voiceBusy,setVoiceBusy]=useState(false),[error,setError]=useState(''),[templateName,setTemplateName]=useState('');
 const ids=useRef(saved?.ids||Array.from({length:8},()=>crypto.randomUUID())),textRef=useRef(content.body),revision=useRef(0),source=useRef(saved?.source||(seed?.version?{sourceId:seed.id,sourceVersion:seed.version}:{}));textRef.current=content.body;
 const draft=useOrgDraft({api,initial:restored,payload:{content,kind,assignment,items,suggestions,manual,advice,ids:ids.current,source:source.current},enabled:true});
 const update=value=>{setManual(old=>[...new Set([...old,...Object.keys(value).filter(k=>k!=='body'&&JSON.stringify(value[k])!==JSON.stringify(content[k]))])]);revision.current++;setContent(value);setItems(null);setSuggestions(null);};
 async function analyze(){setBusy(true);setError('');const rev=revision.current;try{const result=await api('/ai',{method:'POST',body:JSON.stringify({id:crypto.randomUUID(),text:content.body,kind,content,manualFields:manual,consent:true})});if(rev!==revision.current)return;setItems(prepareAiItems(content,result.items,manual));setSuggestions(result.items);setAdvice(result.advice);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function close(){if(busy||voiceBusy)return;try{await draft.flush();if(!content.body.trim()&&!items)await draft.remove();onClose();}catch(e){setError('尚未保存，输入仍在当前页面。'+e.message);}}
 async function save(){setBusy(true);setError('');try{await draft.flush();if(draft.status==='conflict')throw new Error('请先处理草稿冲突');const tasks=(items||[{...content,kind:kind==='auto'?content.kind:kind}]).map((c,i)=>({id:ids.current[i],content:c,assignment,publish:true}));const result=await action('publish-work-draft',{draftId:draft.state.current.id,tasks,...source.current},draft.state.current.version);draft.stop();onCreated(result.taskIds?.[0]);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const show=v=>Array.isArray(v)?v.map(item=>typeof item==='object'?item.text:item).join('、'):typeof v==='boolean'?v?'是':'否':v||'未设置';
 return <Modal wide title={'新建 · '+home.organization.name} onClose={close}><div className="org-form"><div className="org-draft-status" role="status">保存到：{home.organization.name} · {{empty:'等待输入',saved:'草稿已保存',saving:'正在保存草稿…',unsaved:'草稿待保存',conflict:'草稿有版本冲突'}[draft.status]}</div>{draft.error&&<p className="form-error">{draft.error}{draft.status==='conflict'&&<button className="text-button" onClick={()=>draft.fork().catch(e=>setError(e.message))}>将当前输入另存为草稿</button>}</p>}<p className="org-hint">{source.current.sourceId?'仅发布选中的内容，私人原文不会自动同步。':'短暂断网时输入留在当前页面；联网后保存到仅你可见的草稿箱。'}</p>
 <div className="org-inline"><label>整理方式<select disabled={busy||voiceBusy} value={kind} onChange={e=>{setKind(e.target.value);update({...content,kind:e.target.value==='auto'?'task':e.target.value,startAt:null,endAt:null,allDay:false});if(e.target.value==='auto')setManual(old=>old.filter(k=>!['kind','startAt','endAt','allDay'].includes(k)));}}><option value="auto">默认 · AI 判断类别</option><option value="note">想法</option><option value="task">待办</option><option value="event">日程</option></select></label>{home.organization.settings.voiceEnabled&&<VoiceInput workspace={{...workspace,api:(path,opt)=>api(path.replace('/api/voice','/voice'),opt)}} onOpen={()=>{}} onBusy={setVoiceBusy} disabled={busy} onTranscript={text=>{const body=[textRef.current,text].filter(Boolean).join('\n');if(body.length>8000)return false;update({...content,body});return true;}}/>}</div>
 <fieldset disabled={busy||voiceBusy}><ContentFields hideKind value={content} onChange={update}/><button className="button secondary" disabled={!home.organization.settings.aiEnabled||!content.body.trim()||content.body.length>8000} onClick={analyze}>用 Qwen 整理草稿</button><p className="org-hint">{home.organization.settings.aiEnabled?'将本次内容和手填字段发送给百炼。手填信息优先保留，人员与范围由你确认。':'组织尚未开启 AI，默认类别按待办保存。'}</p>
 {items&&<div className="org-ai-result"><strong>整理结果 · {items.length} 项</strong>{items.length>1&&<p className="org-hint">手填信息保留在第 1 项，请逐项核对其余任务。</p>}{suggestions?.[0]&&manual.filter(k=>k!=='body'&&JSON.stringify(content[k])!==JSON.stringify(suggestions[0][k])).map(k=><div className="org-ai-diff" key={k}><strong>{fieldNames[k]}</strong><span>手填：{show(content[k])}</span><span>AI 建议：{show(suggestions[0][k])}</span><button className="text-button" onClick={()=>setItems(old=>old.map((x,i)=>i?x:{...x,[k]:suggestions[0][k]}))}>采用 AI 建议</button><button className="text-button" onClick={()=>setItems(old=>old.map((x,i)=>i?x:{...x,[k]:content[k]}))}>保留手填</button></div>)}{items.map((v,i)=><details key={i} open={items.length===1}><summary>{i+1}. {v.title||v.body.slice(0,40)}</summary><ContentFields compact showChecklist={items.length>1} value={v} onChange={next=>setItems(old=>old.map((x,k)=>k===i?next:x))}/></details>)}{advice.map(s=><p key={s} className="org-hint">{s}</p>)}</div>}
 {(!items||items.length===1)&&<ExecutionPlanEditor value={items?.length===1?items[0]:content} onChange={v=>items?.length===1?setItems([v]):update(v)} home={home} api={api} onBusy={setBusy}/>} {items?.length>1&&<p className="org-hint">拆分后的任务可在各项内容中手动添加清单；单项任务支持 AI 生成执行建议。</p>}<AssignmentFields home={home} value={assignment} onChange={setAssignment}/>{taskQuality(items?.[0]||content,assignment).length>0&&<details className="org-details"><summary>发布前检查 · {taskQuality(items?.[0]||content,assignment).length} 项待补充</summary><ul>{taskQuality(items?.[0]||content,assignment).map(s=><li key={s}>{s}</li>)}</ul></details>}<details><summary>保存为常用模板</summary><label>模板名称<input maxLength={60} value={templateName} onChange={e=>setTemplateName(e.target.value)}/></label><p className="org-hint">保存当前单项内容和分配设置，仅你在本组织可用。模板可用于新建或重复任务。</p><button className="button secondary" disabled={!templateName.trim()||!content.body.trim()||items?.length>1} onClick={async()=>{setBusy(true);try{await action('template',{id:crypto.randomUUID(),name:templateName,content:items?.[0]||content,assignment});setTemplateName('');setError('模板已保存，可在“草稿与模板”中使用。');}catch(e){setError(e.message);}finally{setBusy(false);}}}>保存模板</button></details></fieldset>
 {error&&<p role="alert" className="form-error">{error}</p>}<div className="org-actions org-composer-actions"><button className="button secondary" disabled={busy||voiceBusy} onClick={close}>保留草稿并关闭</button><button className="button primary" disabled={busy||voiceBusy||!content.body.trim()||draft.status==='conflict'} onClick={save}>{busy?'处理中…':`确认发布${items?.length>1?' '+items.length+' 项':''}`}</button></div></div></Modal>;
}
export function ShareComposer({home,seed,action,Modal,onClose,onSaved,existing}){const [content,setContent]=useState(()=>selectedContent(seed)),[visibility,setVisibility]=useState(existing?.visibility||'recipients'),[scopeId,setScopeId]=useState(existing?.scopeId||null),[recipients,setRecipients]=useState(existing?.recipients||[]),[busy,setBusy]=useState(false),[error,setError]=useState('');const id=useRef(existing?.id||crypto.randomUUID());return <Modal title="只读分享 · 预览公开内容" wide onClose={onClose}><form className="org-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await action('share',{id:id.current,sourceId:seed.id,sourceVersion:seed.version,snapshot:content,visibility,scopeId,recipients},existing?.version);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}}><p className="org-hint">仅下方快照对接收范围可见。组织管理员不会自动获得阅读权，后续私人编辑也不会同步。</p><ContentFields value={content} onChange={setContent}/><label>接收范围<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="recipients">指定成员</option><option value="project">所在项目</option><option value="department">所在部门</option><option value="organization">全组织</option></select></label>{visibility==='recipients'?<MemberSelect multiple home={home} label="接收成员" value={recipients} onChange={setRecipients}/>:['project','department'].includes(visibility)?<label>选择范围<select value={scopeId||''} onChange={e=>setScopeId(e.target.value||null)}><option value="">请选择</option>{home.scopes.filter(s=>s.kind===visibility&&s.memberIds.includes(home.me.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>:null}{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>确认分享</button></form></Modal>;}
