import React,{useState,useEffect} from 'react';
import {dayKey} from './model';
export function OrgLibrary({api,action,onCompose,onTask}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[repeat,setRepeat]=useState(null);
 async function refresh(){try{setData(await api('/library'));setError('');}catch(e){setError(e.message);if([401,403,404].includes(e.status))setData(null);}}
 useEffect(()=>{refresh();},[]);
 async function run(fn){setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const frequency={daily:'每天',weekdays:'工作日（周一至周五）',weekly:'每周',monthly:'每月'};
 return <section className="org-form"><p className="org-hint">这里的草稿、模板和重复计划仅你在当前组织可见。发布后的任务按所选范围共享。</p>{error&&<p role="alert" className="form-error">{error}</p>}
 <h2>草稿箱 <small>{data?.drafts.length||0}</small></h2>{data?.drafts.map(d=><article className="org-panel" key={d.id}><strong>{d.title}</strong><p className="org-hint">{d.taskId?'任务编辑':'新建草稿'} · {new Date(d.updatedAt).toLocaleString('zh-CN')}</p><div className="org-actions"><button disabled={busy} className="button primary" onClick={()=>run(async()=>{const restored=await api('/work-drafts/'+d.id);if(d.taskId)onTask(d.taskId,restored);else onCompose({restored});})}>继续编辑</button><button disabled={busy} className="button secondary" onClick={()=>run(()=>action('delete-work-draft',{id:d.id},d.version))}>删除草稿</button></div></article>)}{data&&!data.drafts.length&&<p className="org-hint">输入中的内容会自动保留在这里。</p>}
 <h2>常用模板</h2><p className="org-hint">用模板新建会保留原日期，发布前请核对；重复计划会自动平移日期。</p>{data?.templates.map(t=><article className="org-panel" key={t.id}><strong>{t.name}</strong><p>{t.content.title||t.content.body.slice(0,80)}</p><div className="org-actions"><button disabled={busy} className="button primary" onClick={()=>onCompose({seed:{...t.content,assignment:t.assignment}})}>用模板新建</button><button disabled={busy} className="button secondary" onClick={()=>setRepeat({id:crypto.randomUUID(),templateId:t.id,name:t.name,rule:{frequency:'weekly',interval:1,startDate:dayKey(),endDate:null}})}>建立重复计划</button><button disabled={busy} className="text-button" onClick={()=>run(()=>action('delete-template',{id:t.id},t.version))}>删除模板</button></div></article>)}{data&&!data.templates.length&&<p className="org-hint">在新建页面展开“保存为常用模板”。</p>}
 {repeat&&<form className="org-panel org-form" onSubmit={e=>{e.preventDefault();run(async()=>{const {name,...v}=repeat;await action('repeat',v);setRepeat(null);});}}><h3>重复生成 · {repeat.name}</h3><div className="org-fields"><label>频率<select value={repeat.rule.frequency} onChange={e=>setRepeat({...repeat,rule:{...repeat.rule,frequency:e.target.value,interval:1}})}>{Object.entries(frequency).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{repeat.rule.frequency!=='weekdays'&&<label>间隔（{repeat.rule.frequency==='daily'?'天':repeat.rule.frequency==='weekly'?'周':'月'}）<input type="number" required min={1} max={12} value={repeat.rule.interval} onChange={e=>setRepeat({...repeat,rule:{...repeat.rule,interval:Number(e.target.value)}})}/></label>}<label>首次生成日期<input type="date" required min={dayKey()} value={repeat.rule.startDate} onChange={e=>setRepeat({...repeat,rule:{...repeat.rule,startDate:e.target.value}})}/></label><label>最后生成日期（选填）<input type="date" min={repeat.rule.startDate} value={repeat.rule.endDate||''} onChange={e=>setRepeat({...repeat,rule:{...repeat.rule,endDate:e.target.value||null}})}/></label></div><p className="org-hint">北京时间当天生成独立任务，沿用模板的分配、接收和验收设置。日期随每次生成平移；月末不足对应日时取当月最后一天。工作日不含节假日调休规则。停机或暂停期间的旧任务跳过。</p><div className="org-actions"><button className="button primary" disabled={busy}>启用重复计划</button><button type="button" className="button secondary" onClick={()=>setRepeat(null)}>取消</button></div></form>}
 <h2>重复计划</h2>{data?.repeats.map(r=><article className="org-panel" key={r.id}><strong>{r.name} · {{active:'已启用',paused:'已暂停',finished:'已结束'}[r.state]}</strong><p>{frequency[r.rule.frequency]}{r.rule.interval>1?' · 间隔 '+r.rule.interval:''} · 下一次：{r.nextDate||'无'}</p>{r.error&&<p className="form-error">{r.error}</p>}{r.state!=='finished'&&<div className="org-actions"><button disabled={busy} className="button secondary" onClick={()=>run(()=>action('repeat-state',{id:r.id,state:r.state==='active'?'paused':'active'},r.version))}>{r.state==='active'?'暂停':'恢复'}</button><button disabled={busy} className="text-button" onClick={()=>run(()=>action('repeat-state',{id:r.id,state:'finished'},r.version))}>结束后续重复</button></div>}</article>)}<p className="org-hint">暂停或结束仅影响后续生成，已有任务保留。修改重复内容时，用新模板建立计划，再结束旧计划。</p>
 </section>;
}
