import React,{useEffect,useState,useRef} from 'react';
import {ExecutionPlanEditor,TaskExecution} from './ExecutionPlan';
import {useOrgDraft} from './useOrgDraft';
import {ContentFields,AssignmentFields,MemberSelect,assignmentOf,statuses,quadrants,visibilityLabels} from './OrgForms';
const actionLabels={'checklist-check':'更新检查项','deliverable-add':'添加交付链接','deliverable-state':'调整交付链接',published:'发布任务','draft.created':'保存草稿',content:'调整内容或期限',assignment:'调整分配或权限',start:'开始执行',complete:'提交完成',approve:'验收通过',return:'退回修改',accept:'确认接收',block:'更新阻塞情况',cancel:'取消任务',reopen:'重新打开',archive:'调整归档','resolve-request':'处理变更申请'};
export function OrgTaskDetail(props){
 const [restored,setRestored]=useState(props.restored||null),[ready,setReady]=useState(!!props.restored),[error,setError]=useState('');
 useEffect(()=>{let alive=true;async function load(){try{if(!props.restored){const library=await props.api('/library'),d=library.drafts.find(d=>d.taskId===props.id);if(d){const r=await props.api('/work-drafts/'+d.id);if(alive)setRestored(r);}}if(alive)setReady(true);}catch(e){if(alive)setError(e.message);}}load();return()=>{alive=false;};},[props.id]);
 return ready?<TaskDetailEditor {...props} restored={restored}/>:<props.Modal title="任务详情" onClose={props.onClose}><p>{error||'正在恢复编辑与检查权限…'}</p>{error&&<button className="button secondary" onClick={props.onClose}>关闭后重试</button>}</props.Modal>;
}
function TaskDetailEditor({id,initialAction,home,api,action,Modal,onClose,onChanged,restored}){
 const [delivery,setDelivery]=useState(()=>restored?.payload.delivery||{id:crypto.randomUUID(),label:'',url:''}),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[edit,setEdit]=useState(restored?.payload.edit||null),[note,setNote]=useState(''),[comment,setComment]=useState(restored?.payload.comment||''),[mentions,setMentions]=useState(restored?.payload.mentions||[]);const seq=useRef(0),initialUsed=useRef(!!restored);
 const draft=useOrgDraft({api,initial:restored,taskId:id,payload:{edit,comment,mentions,delivery},enabled:!!data&&(data.task.permissions.edit||data.task.permissions.execute)&&!!(edit||comment||delivery.label||delivery.url||restored)});
 async function close(){if(busy)return;if(comment&&data&&!data.task.permissions.edit&&!data.task.permissions.execute){setError('评论尚未发送，请先发送或清空评论再关闭。');return;}try{await draft.flush();if(!edit&&!comment&&!delivery.label&&!delivery.url&&draft.state.current.version)await draft.remove();onClose();}catch(e){setError(e.message);}}
 async function refresh(){const run=++seq.current;try{const result=await api('/tasks/'+id);if(run===seq.current){setData(result);setError('');if(initialAction&&!initialUsed.current){initialUsed.current=true;setEdit({kind:initialAction,payload:{note:''},version:result.task.version});}}}catch(e){if(run===seq.current){if([401,403,404].includes(e.status)){setData(null);setEdit(null);setComment('');setDelivery({id:crypto.randomUUID(),label:'',url:''});draft.stop();}setError(e.message);}}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>{seq.current++;clearInterval(timer);};},[id]);
 const t=data?.task,p=t?.permissions||{},name=uid=>{const m=home.members.find(m=>m.id===uid);return m?m.name+(m.state==='active'?'':'（已离开组织）'):'未分配';},payloadAction=async(kind,payload,version=t.version)=>{setBusy(true);setError('');try{await draft.flush();await action(kind,{id,payload},version);if(kind===edit?.kind||kind==='comment'||kind==='deliverable-add'){const nextEdit=kind===edit?.kind?null:edit,nextComment=kind==='comment'?'':comment;if(!nextEdit&&!nextComment&&(kind==='deliverable-add'||!delivery.label&&!delivery.url)&&draft.state.current.version){await draft.remove();draft.reset();}setEdit(nextEdit);setComment(nextComment);if(kind==='comment')setMentions([]);if(kind==='deliverable-add')setDelivery({id:crypto.randomUUID(),label:'',url:''});}setNote('');await refresh();onChanged();return true;}catch(e){await refresh();setError(e.message);return false;}finally{setBusy(false);}};
 function openEdit(kind,payload={note:''}){setEdit({kind,payload,version:t.version});}
 const membersVisible={...home,members:home.members.filter(m=>data?.visibleMembers.includes(m.id))};
 return <Modal wide title={t?.content.title||'任务详情'} onClose={close}><div className="org-form">{(edit||comment||delivery.label||delivery.url)&&(data?.task.permissions.edit||data?.task.permissions.execute)&&<p className="org-draft-status" role="status">{draft.status==='saved'?'编辑已保留在草稿箱':draft.status==='saving'?'正在保留编辑…':'编辑待保留，请勿关闭页面'}{draft.error&&' · '+draft.error}{draft.status==='conflict'&&<button className="text-button" onClick={()=>draft.fork().catch(e=>setError(e.message))}>另存当前编辑</button>}</p>}{error&&<p className="form-error" role="alert">{error}</p>}{!t?<p>正在获取当前权限下的任务…</p>:<><div className="org-chips"><span>{statuses[t.status]}</span><span>{name(t.assigneeId)}</span>{t.blockedReason&&<span className="warning">已阻塞</span>}{t.archivedAt&&<span>已归档</span>}<small>版本 {t.version}</small></div><p className="org-body">{t.content.body}</p><div className="org-facts"><span>创建者：{name(t.creatorId)}</span><span>计划：{[t.content.scheduledDate,t.content.scheduledTime].filter(Boolean).join(' ')||'待安排'}</span><span>截止：{[t.content.dueDate,t.content.dueTime].filter(Boolean).join(' ')||'未设置'}</span><span>预计投入：{t.content.durationMinutes?`${t.content.durationMinutes} 分钟`:'未填写'}</span><span>验收人：{name(t.reviewerId)}</span><span>组织优先级：{quadrants[t.content.quadrant]||'待确认'}</span>{t.acceptRequired&&<span>确认接收：{t.acceptedAt?'已确认':'等待负责人确认'}</span>}</div>{t.content.acceptanceCriteria&&<div className="org-callout"><strong>验收标准</strong><p>{t.content.acceptanceCriteria}</p></div>}{t.blockedReason&&<div className="org-callout warning"><strong>阻塞原因</strong><p>{t.blockedReason}</p></div>}{t.completionNote&&<div className="org-callout"><strong>交付说明</strong><p>{t.completionNote}</p></div>}{t.reviewNote&&<div className="org-callout"><strong>处理意见</strong><p>{t.reviewNote}</p></div>}
 <details><summary>可见范围 · {visibilityLabels[t.visibility]}（{data.visibleMembers.length} 人）</summary><p>{data.visibleMembers.map(name).join('、')}</p><p className="org-hint">成员或授权范围变化后，以当前权限为准。</p></details>
 <TaskExecution data={data} home={home} busy={busy} onAction={payloadAction} delivery={delivery} onDeliveryChange={setDelivery}/><div className="org-actions org-detail-actions">{!t.archivedAt&&<>{p.draft&&<button disabled={busy} className="button primary" onClick={()=>payloadAction('publish',{})}>发布草稿</button>}{p.accept&&!t.acceptedAt&&t.acceptRequired&&['todo','doing'].includes(t.status)&&<button disabled={busy} className="button primary" onClick={()=>payloadAction('accept',{})}>确认接收</button>}{p.execute&&t.status==='todo'&&<button disabled={busy} className="button secondary" onClick={()=>payloadAction('start',{})}>开始执行</button>}{p.submit&&['todo','doing'].includes(t.status)&&<button className="button primary" disabled={busy} onClick={()=>openEdit('complete')}>{t.reviewRequired?'提交验收':'完成任务'}</button>}{p.review&&t.status==='review'&&<><button className="button primary" disabled={busy} onClick={()=>openEdit('approve')}>验收通过</button><button className="button secondary" disabled={busy} onClick={()=>openEdit('return')}>退回修改</button></>}{p.execute&&['todo','doing','review'].includes(t.status)&&<><button className="button secondary" disabled={busy} onClick={()=>openEdit('block',{note:t.blockedReason})}>反馈阻塞</button><button className="button secondary" disabled={busy} onClick={()=>openEdit('request',{kind:'deadline',reason:'',dueDate:t.content.dueDate,dueTime:t.content.dueTime,assigneeId:t.assigneeId})}>提出变更</button></>}{p.edit&&<><button className="button secondary" disabled={busy} onClick={()=>openEdit('content',t.content)}>编辑内容与期限</button><button className="button secondary" disabled={busy} onClick={()=>openEdit('assignment',assignmentOf(t))}>分配与权限</button></>}{p.manage&&['done','cancelled','review'].includes(t.status)&&<button className="button secondary" disabled={busy} onClick={()=>openEdit('reopen')}>重新打开</button>}{p.manage&&!['done','cancelled'].includes(t.status)&&<button className="button secondary" disabled={busy} onClick={()=>openEdit('cancel')}>取消任务</button>}</>}{p.manage&&(t.archivedAt||['done','cancelled'].includes(t.status))&&<button className="button secondary" disabled={busy} onClick={()=>payloadAction('archive',{})}>{t.archivedAt?'恢复归档':'归档'}</button>}</div>
 {edit&&<form className="org-callout org-edit" onSubmit={e=>{e.preventDefault();payloadAction(edit.kind,edit.payload,edit.version);}}><fieldset disabled={busy}><strong>{actionLabels[edit.kind]||{request:'变更申请',content:'编辑内容与期限',assignment:'分配与权限'}[edit.kind]}</strong>{edit.kind==='content'?<><ContentFields value={edit.payload} onChange={payload=>setEdit({...edit,payload})}/>{['draft','todo','doing'].includes(t.status)&&<ExecutionPlanEditor value={edit.payload} onChange={payload=>setEdit({...edit,payload})} home={home} api={api} taskId={t.id} taskVersion={edit.version} onBusy={setBusy}/>}</>:edit.kind==='assignment'?<AssignmentFields home={home} value={edit.payload} onChange={payload=>setEdit({...edit,payload})}/>:edit.kind==='request'?<><label>申请类型<select value={edit.payload.kind} onChange={e=>setEdit({...edit,payload:{...edit.payload,kind:e.target.value}})}><option value="deadline">调整截止</option><option value="reassign">改派负责人</option><option value="cancel">取消任务</option><option value="clarify">需要澄清</option></select></label>{edit.payload.kind==='deadline'&&<label>建议截止日期<input type="date" value={edit.payload.dueDate||''} onChange={e=>setEdit({...edit,payload:{...edit.payload,dueDate:e.target.value||null}})}/></label>}{edit.payload.kind==='reassign'&&<MemberSelect home={home} label="建议负责人" value={edit.payload.assigneeId} onChange={assigneeId=>setEdit({...edit,payload:{...edit.payload,assigneeId}})}/>}<label>说明原因<textarea required maxLength={3000} value={edit.payload.reason} onChange={e=>setEdit({...edit,payload:{...edit.payload,reason:e.target.value}})}/></label></>:<label>{edit.kind==='block'?'阻塞原因（留空表示已解除）':edit.kind==='complete'?'交付结果或完成说明':'处理说明'}<textarea maxLength={3000} value={edit.payload.note} onChange={e=>setEdit({...edit,payload:{note:e.target.value}})}/></label>}<div className="org-actions"><button className="button primary" disabled={busy}>确认</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>取消编辑</button></div></fieldset></form>}
 <details><summary>我的安排与通知（不会修改组织期限或优先级）</summary><div className="org-fields"><label className="check-label"><input type="checkbox" checked={!!t.preference.muted} onChange={e=>payloadAction('task-preference',{muted:e.target.checked,snoozeMinutes:0,quadrant:t.preference.quadrant||null,focusDate:t.preference.focusDate||null})}/>将本任务微信通知静音</label><label>我的四象限<select value={t.preference.quadrant||''} onChange={e=>payloadAction('task-preference',{muted:!!t.preference.muted,snoozeMinutes:0,quadrant:e.target.value||null,focusDate:t.preference.focusDate||null})}><option value="">沿用组织优先级</option>{Object.entries(quadrants).map(([k,s])=><option key={k} value={k}>{s}</option>)}</select></label><label>我的重点日期<input type="date" value={t.preference.focusDate||''} onChange={e=>payloadAction('task-preference',{muted:!!t.preference.muted,snoozeMinutes:0,quadrant:t.preference.quadrant||null,focusDate:e.target.value||null})}/></label><button className="button secondary" disabled={busy} onClick={()=>payloadAction('task-preference',{muted:!!t.preference.muted,snoozeMinutes:30,quadrant:t.preference.quadrant||null,focusDate:t.preference.focusDate||null})}>30 分钟后再提醒我</button></div></details>
 {data.requests.length>0&&<section><h3>变更申请</h3>{data.requests.map(r=><div className="org-callout" key={r.id}><strong>{name(r.userId)} · {{deadline:'调整截止',reassign:'改派',cancel:'取消',clarify:'澄清'}[r.kind]} · {{pending:'待处理',approved:'已同意',rejected:'已退回'}[r.state]}</strong><p>{r.reason}</p>{r.kind==='deadline'&&<p>建议截止：{r.proposal.dueDate||'移除截止日期'}</p>}{r.kind==='reassign'&&<p>建议负责人：{name(r.proposal.assigneeId)}</p>}{r.resolution&&<p>{r.resolution}</p>}{r.state==='pending'&&p.manage&&<><label>处理说明<input maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="org-actions"><button className="button primary" disabled={busy||r.baseVersion!==t.version} onClick={()=>payloadAction('resolve-request',{requestId:r.id,approved:true,note})}>同意</button><button className="button secondary" disabled={busy} onClick={()=>payloadAction('resolve-request',{requestId:r.id,approved:false,note})}>退回</button></div>{r.baseVersion!==t.version&&<p className="org-hint">任务已有更新，请退回后重新申请。</p>}</>}</div>)}</section>}
 {t.status!=='draft'&&<section><h3>讨论</h3>{data.comments.map(c=><div className="org-comment" key={c.id}><small>{name(c.userId)} · {new Date(c.createdAt).toLocaleString('zh-CN')}</small><p>{c.body}</p></div>)}<form onSubmit={async e=>{e.preventDefault();if(await payloadAction('comment',{body:comment,mentions})){setComment('');setMentions([]);}}}>{!p.edit&&!p.execute&&<p className="org-hint">评论在发送前仅保留在当前页面。</p>}<label>添加评论<textarea rows={2} maxLength={3000} required value={comment} onChange={e=>setComment(e.target.value)}/></label><details><summary>提及成员</summary><MemberSelect multiple home={membersVisible} label="通知这些成员" value={mentions} onChange={setMentions}/></details><div className="org-actions"><button className="button secondary" disabled={busy||!comment.trim()}>发表评论</button>{comment&&<button type="button" className="text-button" onClick={()=>{setComment('');setMentions([]);}}>清空评论</button>}</div></form></section>}
 <details><summary>变更记录 · {data.events.length}</summary>{data.events.map(e=><div key={e.id} className="org-comment"><small>{new Date(e.createdAt).toLocaleString('zh-CN')} · {name(e.actorId)}</small><p>{actionLabels[e.action]||e.action}{e.detail.note?' · '+e.detail.note:''}</p>{e.action==='content'&&<p className="org-hint">截止：{e.detail.from?.dueDate||'无'} → {e.detail.to?.dueDate||'无'}</p>}{e.action==='checklist-check'&&<p>{e.detail.text} · {e.detail.done?'已完成':'已取消勾选'}</p>}{e.action.startsWith('deliverable-')&&<p>{e.detail.label}{e.action==='deliverable-state'?(e.detail.removed?' · 已移除':' · 已恢复'):''}</p>}{e.action==='assignment'&&<p className="org-hint">负责人：{name(e.detail.from?.assigneeId)} → {name(e.detail.to?.assigneeId)}；范围：{visibilityLabels[e.detail.to?.visibility]}</p>}</div>)}</details>
 </>}</div></Modal>;
}
