import React,{useEffect,useState} from 'react';
import {Check,Clock,Bell,LoaderCircle} from 'lucide-react';
import {dateLabel,timeLabel,titleOf} from './model';
const deliveryNames={pending:'等待发送',sending:'正在发送',retry:'稍后重试',queued:'已提交，等待平台回执',delivered:'平台报告已投递',failed:'平台报告发送失败',unknown:'投递结果未确认',cancelled:'推送已取消'};
export function ReminderDialog({id,workspace,Modal,onClose,onEdit}){
  const [data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[snooze,setSnooze]=useState(false);
  useEffect(()=>{let alive=true;const load=()=>workspace.api(`/api/reminders/${id}`).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load();},5000);return()=>{alive=false;clearInterval(timer);};},[id,workspace.api]);
  async function respond(action,minutes){setBusy(true);setError('');try{await workspace.flush();const result=await workspace.api(`/api/reminders/${id}/action`,{method:'POST',body:JSON.stringify({action,version:data.entry.version,...(minutes?{minutes}:{})})});setData(result);setSnooze(false);await workspace.sync();}catch(e){setError(e.message);const latest=await workspace.api(`/api/reminders/${id}`).catch(()=>null);if(latest)setData(latest);}finally{setBusy(false);}}
  const closed=data?.entry.status!=='active',handled=['done','snoozed'].includes(data?.response?.action);
  return <Modal title="处理提醒" onClose={onClose}><div className="reminder-dialog">{!data&&!error&&<p><LoaderCircle className="spin" size={16}/>正在打开提醒…</p>}{data&&<><h3>{titleOf(data.entry)}</h3><p className="reminder-body">{data.entry.body}</p><div className="reminder-state"><Bell size={14}/>{deliveryNames[data.delivery.state]||'等待确认'}</div>{data.response&&<p className="reminder-response" role="status"><Check size={16}/>{data.response.action==='done'?'已完成':data.response.action==='snoozed'?`已延后至 ${dateLabel(data.response.snoozeUntil)} ${timeLabel(data.response.snoozeUntil)}`:'已知晓'}<small>{dateLabel(data.response.respondedAt)} {timeLabel(data.response.respondedAt)}</small></p>}
    <div className="reminder-buttons"><button className="button secondary" disabled={busy||Boolean(data.response)||!workspace.online} onClick={()=>respond('acknowledged')}>已知晓</button>{data.entry.kind==='task'&&<button className="button primary" disabled={busy||closed||handled||!workspace.online} onClick={()=>respond('done')}>已完成</button>}<button className="button secondary" disabled={busy||closed||handled||!workspace.online} onClick={()=>setSnooze(!snooze)}><Clock size={15}/>稍后提醒</button></div>
    {snooze&&<div className="snooze-options">{[15,30,60].map(minutes=><button key={minutes} disabled={busy} onClick={()=>respond('snoozed',minutes)}>{minutes===60?'1 小时后':`${minutes} 分钟后`}</button>)}</div>}
    <button className="text-button reminder-edit" onClick={()=>{onClose();onEdit(data.entry);}}>查看和编辑记录</button></>}{error&&<p className="form-error" role="alert">{error}</p>}</div></Modal>;
}
