const DB='joybeat-me-accounts-v2';
let connection;
function open(){return connection??=new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('state');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function readState(userId){if(!userId)throw new Error('Account required');const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('state'),request=tx.objectStore('state').get(userId);request.onsuccess=()=>resolve(request.result??{entries:[],queue:[],draft:''});request.onerror=()=>reject(request.error);});}
export async function updateState(userId,update){if(!userId)throw new Error('Account required');const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite'),table=tx.objectStore('state'),request=table.get(userId);let next;request.onsuccess=()=>{try{const previous=request.result??{entries:[],queue:[],draft:''};next=typeof update==='function'?update(previous):update;table.put(next,userId);}catch(error){tx.abort();reject(error);}};tx.oncomplete=()=>resolve(next);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??new Error('本机保存未完成'));});}
export async function clearUserState(userId){const old=await readState(userId);if(old.legacyRecovered)await clearLegacyState();const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').delete(userId);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export async function recoverLegacyState(user){if(user.role!=='owner')return;const current=await readState(user.id);if(current.legacyRecovered)return;const legacy=await new Promise(resolve=>{const request=indexedDB.open('joybeat-me-v1');request.onsuccess=()=>{const db=request.result;if(!db.objectStoreNames.contains('state')){db.close();return resolve(null);}const tx=db.transaction('state'),read=tx.objectStore('state').get('main');read.onsuccess=()=>resolve(read.result);read.onerror=()=>resolve(null);tx.oncomplete=()=>db.close();};request.onerror=()=>resolve(null);});await updateState(user.id,previous=>({...((!previous.entries.length&&!previous.queue.length&&legacy)?legacy:previous),legacyRecovered:true}));}

async function clearLegacyState(){await new Promise((resolve,reject)=>{const r=indexedDB.open('joybeat-me-v1');r.onsuccess=()=>{const db=r.result;if(!db.objectStoreNames.contains('state')){db.close();resolve();return;}const tx=db.transaction('state','readwrite');tx.objectStore('state').delete('main');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};};r.onerror=()=>reject(r.error);});}
